### ISSUE TITLE
Container not working on a Qnap ARM based NAS

### ISSUE THREAD

**Issue by alc86** [linuxserver/docker-unifi-controller#10]
I tried to run the container on my QNAP Nas with ARM CPU ( [https://www.qnap.com/de-de/product/ts-431xeu](https://www.qnap.com/de-de/product/ts-431xeu) ) but the WebUI is not reachable.

This are the steps which I have done:
1.  create a new user
![New_User](https://user-images.githubusercontent.com/29775093/57130993-8cbbff00-6d9b-11e9-8a67-c74513098fa0.jpg)

2. connect with putty to the Nas to get PUID, PGID
![Putty_PUID_PGID](https://user-images.githubusercontent.com/29775093/57131185-ec1a0f00-6d9b-11e9-95ca-81bba41f89f3.jpg)

3. Create container at container station 
![Create_Container_1](https://user-images.githubusercontent.com/29775093/57131423-9d20a980-6d9c-11e9-8d21-c038bb27357b.jpg)
![Create_Container_3](https://user-images.githubusercontent.com/29775093/57131427-a01b9a00-6d9c-11e9-9a7a-8dc2a3c16b97.jpg)
![Create_Container_2](https://user-images.githubusercontent.com/29775093/57131430-a1e55d80-6d9c-11e9-9d4f-f04b341d1a05.jpg)
![Create_Container_Summery](https://user-images.githubusercontent.com/29775093/57131505-dc4efa80-6d9c-11e9-8dc6-d17f13532ebd.jpg)

4.) Run the new container
![Run_Container_1](https://user-images.githubusercontent.com/29775093/57131792-d0176d00-6d9d-11e9-8549-a482e69d6588.jpg)
![Run_Container_2](https://user-images.githubusercontent.com/29775093/57131807-de658900-6d9d-11e9-9674-f17f1a8ebab8.jpg)

5.) Run Terminal
 apt-get update
![Terminal_apt_get_update](https://user-images.githubusercontent.com/29775093/57132047-9c891280-6d9e-11e9-9f8d-06c73e5e1a21.jpg)
apt-get install execstack
![Terminal_apt_get_install_execstack](https://user-images.githubusercontent.com/29775093/57132118-cfcba180-6d9e-11e9-896a-1dbb6ad454ec.jpg)
execstack -c /usr/lib/unifi/lib/native/Linux/armv7/libubnt_webrtc_jni.so
![Terminal_execstack](https://user-images.githubusercontent.com/29775093/57132209-276a0d00-6d9f-11e9-9919-f98d1dd0e5ba.jpg)

6.) Restart container

**Comment by tobbenb** [comment]
You have not mapped any ports to the host. You only set the container ports from what I understand from the screenshots.
Also, don't do any updates inside the container or try to fix anything.

**Comment by alc86** [comment]
the ports are automatically definied.
![Container_Ports](https://user-images.githubusercontent.com/29775093/57133537-639f6c80-6da3-11e9-8043-e095d6b97775.jpg)

**Comment by CHBMB** [comment]
The ports are completely different, I don't see how this could work with that sort of port mapping.
