### ISSUE TITLE
Docker container issuing memory errors and not starting correctly

### ISSUE THREAD

**Issue by nickcj931** [linuxserver/docker-unifi-controller#11]
### Host details
Operating System: Clear Linux OS
Kernel: Linux 5.0.13-752.native
Architecture: x86-64 (Intel NUC)

### Docker details
**Client:**
 Version:           18.06.2
 API version:       1.38
 Go version:        go1.12.4
 Git commit:        e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
 Built:             Thu Apr 18 01:44:38 2019
 OS/Arch:           linux/amd64
 Experimental:      false

**Server:**
 Engine:
  Version:          18.06.2
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.12.4
  Git commit:       e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
  Built:            Thu Apr 18 01:44:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false

### Background
I have tested my configs on my mac docker instance and everything is working fine. However when I try creating the container in my main server (intel-NUC above^^) things just don't want to behave! 
I've deployed with docker run / compose and Portainer, just to see if I'm doing anything stupid, still same outcomes, again replicating the same on my docker for mac (which works fine!)

I have also stripped the config to its bare bones and just literally trying to hit the https://<ip>:8443 screen. Still nothing and the same boot-up sequence with errors is observed.

Final throw at the dice, I have even tried to pass the following env-variables
`JAVA_OPTS = -XX:+UnlockExperimentalVMOptions XX:+UseCGroupMemoryLimitForHeap` thinking it might be related to the Java and Docker not working well together in v8 which is what I believe unifi works with in present controller version.

### Log
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 10-adduser: executing... ,
usermod: no changes,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
We gratefully accept donations at:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,

User uid:    911,
User gid:    911,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 20-config: executing... ,
[cont-init.d] 20-config: exited 0.,
[cont-init.d] 30-keygen: executing... ,
library initialization failed - unable to allocate file descriptor table - out of memory/var/run/s6/etc/cont-init.d/30-keygen: line 7:   220 Aborted                 (core dumped) keytool -genkey -keyalg RSA -alias unifi -keystore /config/data/keystore -storepass aircontrolenterprise -keypass aircontrolenterprise -validity 1825 -keysize 4096 -dname "cn=unifi",
chown: cannot access '/config/data/keystore': No such file or directory,
[cont-init.d] 30-keygen: exited 1.,
[cont-init.d] 99-custom-scripts: executing... ,
[custom-init] no custom scripts found exiting...,
[cont-init.d] 99-custom-scripts: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
library initialization failed - unable to allocate file descriptor table - out of memorylibrary initialization failed - unable to allocate file descriptor table - out of memorylibrary initialization failed - unable to allocate file descriptor table - out of memorylibrary initialization failed - unable to allocate file descriptor table - out of memorylibrary initialization failed - unable to allocate file descriptor table - out of memorylibrary initialization failed - unable to allocate file descriptor table - out of memorylibrary initialization failed - unable to allocate file descriptor table - out of memorylibrary initialization failed - unable to allocate file descriptor table - out of memorylibrary initialization failed - unable to allocate file descriptor table - out of memorylibrary initialization failed - unable to allocate file descriptor table - out of memorylibrary initialization failed - unable to allocate file descriptor table - out of memorylibrary initialization failed - unable to allocate file descriptor table - out of 
```

The `library initialization failed - unable to allocate file descriptor table - out of memory` starts to cycle on and on after around 2min of container start.

### My simple config from Portainer screen grab
<img width="1656" alt="Screenshot 2019-05-09 at 11 22 03" src="https://user-images.githubusercontent.com/17556895/57446641-1280f400-724d-11e9-98b5-0df4ba339c49.png">

Not entirely sure if this is related to issue #2?

I am also getting exactly the same results with unifi-video controller, however I feel its too much of a coincidence that these are the only java containers in my environment and both are failing to start properly on my server. 

Any guidance/wisdom would be greatly appreciated :)

**Comment by tobbenb** [comment]
You have not set the PUID & PGID. Looks like you don't have write permissions to the folder you volume mount /config. 
 Post your complete deployment of the container.

**Comment by nickcj931** [comment]
@tobbenb thanks for the reply. 

I've just left PUID and PGID on default (911 if you don't specify). I have tried it with setting both as 1000 but didn't think it was relevant since I am not bind mounting anything to the container or migrating from an old instance etc.

Below is a new docker compose file which I've just spun up with same errors:

```
version: "2"
services:
  unifi-controller:
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    restart: unless-stopped
```

**Comment by tobbenb** [comment]
Did read carefully enough the first post.
how much memory do you have? It goes out of memory when generating a key before unifi is started.
Could you try to update your docker version?

**Comment by nickcj931** [comment]
Server has 16GB RAM, plenty. MAC has 16GB also and is running much hotter than the server in terms of RAM utilisation.

Docker version posted in OP for my Host OS-  Clear Linux is the latest I can install as part of Clear Linux bundles.

**Comment by thelamer** [comment]
Where did you install Docker from? that is not the current CE version:

https://docs.docker.com/install/linux/docker-ce/ubuntu/

You should also bind mount the config directory to a local folder after you update your Docker engine: 
```
    volumes:
      - /home/myusername/unifi:/config
```
Just make the directory on your server beforehand:
```
mkdir ~/unifi
```

Also Github is not for personal support requests, I appreciate the amount of information you have provided but I am fairly confident this is not an actual bug report, just a learning curve. 

Please hop on our discord for further assistance : 
https://discord.gg/YWrKVTn

**Comment by nickcj931** [comment]
@thelamer cheers for the comment, not really using this as a personal support channel, so might need to get off your high horse buddy.

It seemed like a bug based on what I've used and done in the past. And the fact Java + Docker = Memory issues seemed the right fit.

Docker is pre-packaged as part of Clear Linux https://clearlinux.org/documentation/clear-linux/tutorials/docker

**Comment by tobbenb** [comment]
Thelamer is not on a high horse.
This is not a Java thing, as your memory problem starts before even starting unifi.
It is a local issue to you or Clear Linux/docker issue. Please continue this on either discord or our forum (link in the Readme).
My last advice here is to install the official docker ce version.

**Comment by bswinnerton** [comment]
@nickcj931 I ran into the exact same problem, no luck on the Discourse. I believe that Clear Linux is the root cause of the problem, I believe that they pushed out a change which changes the container runtime from `runc` to `kata` but have been unable to verify.

**Comment by burntoc** [comment]
@nickcj931 @bswinnerton Hey fellas, did you ever figure this out? I've running on a pretty fresh Unbuntu 20.04 install on a Pi 4 and this is really the only one of about a dozer containers I have that is giving me a headache.  I'm getting the exact same behavior, and it's reporting no permissions errors so I don't know what's up.  Maybe it isn't a bug, but I see this issue reported in a number of different distros and it seems to be related to how they handle Java, so maybe there could be some handling change to mitigate this?

**Comment by gagefox** [comment]
library initialization failed - unable to get max # of allocated fds

having a similar problem

**Comment by boisei0** [comment]
Upgraded to Ubuntu 20.04 LTS from Ubuntu 19.10 a couple days ago, Pi 4 4GB edition, on ARM64 architecture. Same problem as the people mentioned above. Under 19.10 it ran without any issues. Since the upgrade to 20.04 I'm seeing the "library initialization failed - unable to get max # of allocated fds", with the following docker-compose file.
```
---
version: "2"
services:
    unifi-controller:
        image: linuxserver/unifi-controller
        container_name: unifi-controller
        environment:
          - PUID=1000
          - PGID=1000
          - MEM_LIMIT=1024M
        volumes:
          - /home/ubuntu/docker/unifi-controller/data:/config
        ports:
          - 3478:3478/udp
          - 10001:10001/udp
          - 8080:8080
          - 8081:8081
          - 8443:8443
          - 8843:8843
          - 8880:8880
          - 6789:6789
        restart: unless-stopped
```

**Comment by kzemek** [comment]
The problem on Ubuntu 20.04 ARM64 seems to be an issue of container privileges, since `privileged: true` fixes the issue. I didn't pry any deeper so far.

**Comment by JanHBade** [comment]
@kzemek 
same for me here

**Comment by mike-code** [comment]
Just for @thelamer information. His request for help or bug report was not personal. It happened to me (and others) as well. `docker stats` showed ~30MB out of 3.73GB limit while top reported >3G memory available.

**Comment by peterpeerdeman** [comment]
same problem here on raspberrypi 4 20.04 arm64
