### ISSUE TITLE
AC/AP reboot can't auto adopt

### ISSUE THREAD

**Issue by chenmnkken** [linuxserver/docker-unifi-controller#127]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
When unifi controller or AP reboot, unifi controller will auto adopt the AP.

## Current Behavior
When unifi controller or AP reboot, unifi controller can't auto adopt the AP.

## Environment
**OS:** Raspberry Pi OS
**CPU architecture:** arm32
**How docker service was installed:**
From the official docker repo.
Unifi controller version is 6.5.55.
AP: UniFi U6 Lite, firmware version is 5.60.23.13051.

## Command used to create docker container (run/create/compose/screenshot)
```
docker run -d \
  --name=unifi-ac \
  -e PUID=1000 \
  -e PGID=1000 \
  -p 3478:3478/udp \
  -p 10001:10001/udp \
  -p 8080:8080 \
  -p 8443:8443 \
  -p 1900:1900/udp `#optional` \
  -p 8843:8843 `#optional` \
  -p 8880:8880 `#optional` \
  -p 6789:6789 `#optional` \
  -p 5514:5514/udp `#optional` \
  -v /home/xxx/unifi:/config \
  --restart unless-stopped \
  linuxserver/unifi-controller
```

### set-inform
First, set-inform,`set-inform http://192.168.0.7:8080/inform`, it's work, the AP is adopted.

### Reboot unifi controller

After reboot unifi controller, the AP is can't adopt, find the AP log, got the inform IP changed error.

From AP system /var/log/messages file.

```
daemon.info mcad: mcad[2323]: ace_wss.ace_wss_reconnect(): url changed form 'http://192.168.0.7:8080/inform' to 'http://172.17.0.2:8080/inform'
```

192.168.0.7 is my Raspberry IP, when unifi controller reboot, the url change to 172.17.0.2, the 172 is my docker container IP.

Next log is all 172 can't connect error.

```
daemon.err mcad: mcad[2323]: ace_reporter_trsp_curl.check_multi_info(): inform failed with curl code 28
daemon.err mcad: mcad[2323]: ace_reporter.reporter_fail(): Timeout (http://172.17.0.2:8080/inform)
daemon.err mcad: mcad[2323]: ace_reporter.reporter_fail(): initial contact failed #1, url=http://172.17.0.2:8080/inform, rc=4
```

I try to set docker container network is host, the problem is fixed, the AP is adopted.

```
docker run -d \
  --name=unifi-ac \
  --network=host \
  -e PUID=1000 \
  -e PGID=1000 \
  -v /home/xxx/unifi:/config \
  --restart unless-stopped \
  linuxserver/unifi-controller
```

**Comment by TheSpad** [comment]
https://github.com/linuxserver/docker-unifi-controller#application-setup

**Comment by chenmnkken** [comment]
Sorry, I didn't read the documentation carefully about set-inform, I try to set the controller host IP, it's work done.
Thanks very much!
