### ISSUE TITLE
Bug report: can not activate automatic backups

### ISSUE THREAD

**Issue by cuthulino** [linuxserver/docker-unifi-controller#136]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
When Ienable automatic backups and save the settings, the settings get saved and backups will be scheduled.

## Current Behavior
When I try to enable automatic backups and save the settings an error appears: "There was an error saving the Backup changes."

## Steps to Reproduce
1. start docker container Versions 7.0.25
2. retore a backup or create new login
3. goto settings -> backup
4. try to activate automatic backups and save it

## Environment
**OS: Ubuntu**
**CPU architecture:** x86_64
**How docker service was installed: Docker Compose in Portainer from Dockerhub**

## Command used to create docker container (run/create/compose/screenshot)
```services:
  unifi-controller:
    image: linuxserver/unifi-controller:7.0.25
    container_name: unifi-controller
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      MEM_LIMIT: 1024 
      MEM_STARTUP: 1024 
    volumes:
      - config:/config
    networks:
      mgmt_vlan:
        ipv4_address: 10.10.1.12
    
volumes:
  config:
    name: unifi_config
    
networks:
  mgmt_vlan:
    name: mgmt_net
    external: true
```

## Docker logs
Only one Error in there:
Exception in thread "Thread-10" java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: destroy called
	at com.ubnt.ace.Launcher.new(Unknown Source)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1172)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.getBeanFactory(AbstractRefreshableApplicationContext.java:168)
	at com.ubnt.service.C.Ö00000(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

**Comment by j0nnymoe** [comment]
I can only assume this could be an issue caused by the backup you're restoring initially. 
Please re-open this issue if this is still a problem.
