### ISSUE TITLE
New install - Web error - HTTP 404 - Not Found

### ISSUE THREAD

**Issue by jwillmer** [linuxserver/docker-unifi-controller#142]
Same behavior as with all others that report this bug. 

I run the docker container on a Raspberry Pi 4 with the default docker-compose file that is provided by the project. For testing I removed the volume mount but it had no different effect. I also checked the permissions with the once mentioned in the other bug reports - all valid. 

When I tested the same docker-compose file on my local x86 machine the setup was there immediately. Could it be that the container has an issue with ARM 32/64 architecture?

Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 15-install: executing...
*** installing unifi packages ***
Selecting previously unselected package unifi.
(Reading database ... 9130 files and directories currently installed.)
Preparing to unpack /app/unifi.deb ...
Unpacking unifi (7.1.65-17871-1) ...
Setting up unifi (7.1.65-17871-1) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Processing triggers for systemd (229-4ubuntu21.31) ...
[cont-init.d] 15-install: exited 0.
[cont-init.d] 19-deprecate: executing...
[cont-init.d] 19-deprecate: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by j0nnymoe** [comment]
Marked as invalid as you haven't provided the requested information in the issue template.

**Comment by jwillmer** [comment]
Docker logs added to prevent you from just discarding the bug.

**Comment by j0nnymoe** [comment]
@jwillmer still need to know what hardware / OS you're using.

**Comment by jwillmer** [comment]
actually while I think of reasons why this happens: i saw that this image uses some mongo database in one issue. if that is the case then this might be the issue since mongo does not support arm 32. 

will add the hardware in a sec

**Comment by j0nnymoe** [comment]
Yep, mono hasn't supported 32bit for a while, we plan to drop 32bit support for this image next month: https://info.linuxserver.io/issues/2021-11-25-unifi/

**Comment by jwillmer** [comment]
ok, then I close this since I don't want to install a new os onto my pi.

**Comment by j0nnymoe** [comment]
Issue you've got is, this is the way things are going, 32bit is on life support. We've done an article on it here: https://www.linuxserver.io/blog/end-of-an-arch

If your hardware is able to run a 64bit OS, you would benefit from switching to a 64bit OS.

**Comment by jwillmer** [comment]
I know, my Pi already runs on 64Bit kernel but there is no in place upgrade for userland and I don't want to reinstall/reconfigure my system 😞
