### ISSUE TITLE
Credentials don't work anymore after migration

### ISSUE THREAD

**Issue by freakbn777** [linuxserver/docker-unifi-controller#147]
Hello,

I backuped /config from an existing unifi-controller for pi 4 (arm32) and restored in a amd64 container in a VM  (with this procedure: https://docs.docker.com/storage/volumes/#backup-restore-or-migrate-data-volumes).
I use recommanded docker-compose on both.
I didn't do the initial setup on new one and I restored /config.
Now I can reach usual login page but my credentials don't work anymore (password manager so I didn't forget it and there is no mistake). 
I also tried ubnt, no success.
I also tried password reset link, I don't receive any mail

**Comment by aptalca** [comment]
I don't believe the config folder is transferable between 32bit and 64bit. You'd need to export your config and restore on the new system.

**Comment by freakbn777** [comment]
I finally get my old unifi-controller back by downgrading to image v7.1.65, so now I can export config like you suggest. Thanks for your help

**Comment by freakbn777** [comment]
Thanks, can be closed
