### ISSUE TITLE
WebUI Wont Load? 8080 Works but not 8443

### ISSUE THREAD

**Issue by betty02** [linuxserver/docker-unifi-controller#150]
Hi All,

Quite new to docker etc. So I have docker installed on my Mac, I run portainer to help me learn. Anyway have installed your docker image and mapped the ports required etc.

When I got to localhost:8443 I get nothing, if I add in https:// I get a cert warning, accepted it to proceed then just get a blank page? If I go to 8080 I get the full setup page etc but then at the end says invalid username and password which I read is because this has to be setup on 8443.

What sort of troubleshooting should I be doing here? Followed a YouTube video, the guides etc and just can't get any activity to setup properly?

Apologies for my lack of knowledge!

Thanks
Simon

**Comment by Roxedus** [comment]
Please follow the issue template

**Comment by betty02** [comment]
Invalid formatting
