### ISSUE TITLE
Read.me needs updating to reflect 7.1.66 no longer works on 32 bit OSes.

### ISSUE THREAD

**Issue by slochewie** [linuxserver/docker-unifi-controller#152]
Upgraded a Raspberry Pi running Raspberry Pi OS 32 bit to 7.1.66. Errors in the attached screen shots. Setting privileged to True will clear the error and allow the controller to start without errors but it is inaccessible from a web browser or the UniFi iOS app. Rolling back to 7.1.65 restores usability. Didn't see the new message in the log that it won't work on 32 bit till after upgrading. Just FYI. ![image](https://user-images.githubusercontent.com/65009367/175866035-819bf4e4-e647-447e-ba67-992203d67503.png)

After setting privileged to True.
![image](https://user-images.githubusercontent.com/65009367/175866056-8008891a-ba36-4349-89b6-30dc4a0fee92.png)

**Comment by j0nnymoe** [comment]
We announced support for 32bit was being dropped last month https://info.linuxserver.io/issues/2022-05-31-unifi-controller/ (with the first announcement mentioned 6 months ago)

![Screenshot_20220627-063927_Firefox~2](https://user-images.githubusercontent.com/10374553/175867474-83c7c353-74f9-4130-a053-14b71a5dce51.png)
Also, under Supported Architectures shows that armhf is no longer supported.

I suggest you look at upgrading to a 64bit OS if your RPI is able to as you're going to hit this issue more and more with containers moving forward.
