### ISSUE TITLE
32 bit ARM no longer supported

### ISSUE THREAD

**Issue by irvintim** [linuxserver/docker-unifi-controller#154]
The "arm32v7-latest" version doesn't work due to Ubiquiti no longer supporting 32 bit ARM processors.  When this version starts up the following is appearing in the logs:

```
unifi-controller    |     ********************************************************
unifi-controller    |     ********************************************************
unifi-controller    |     *                                                      *
unifi-controller    |     *                         !!!!                         *
unifi-controller    |     *     This Unifi-Controller image does not support     *
unifi-controller    |     *   32 bit ARM due to lack of available OS packages    *
unifi-controller    |     *                                                      *
unifi-controller    |     *                                                      *
unifi-controller    |     ********************************************************
unifi-controller    |     ********************************************************
```

This explains why (https://info.linuxserver.io/issues/2021-11-25-unifi/):
```
Unifi Controller 32-bit ARM Deprecation Notice
November 25, 2021 at 12:00 AM


Due to a lack of upstream support for mongodb on 32 bit platforms, we have made the decision to deprecate our 32 bit ARM (also known as armhf / armv7) Unifi Controller image. We will continue to update the image until June 2022 at which point it will cease to be supported.

If you are currently running the Unifi Controller image on a 32 bit ARM platform we recommend you look at alternative options such as upgrading to a 64 bit OS if your hardware supports it.
```

**Comment by j0nnymoe** [comment]
Yes this container no longer has 32bit support due to the reasons mentioned but we also display this in our readme's 
![image](https://user-images.githubusercontent.com/10374553/178156265-4080eb7b-6ff1-42f1-ad7a-392b159b80e5.png)

**Comment by zimmertr** [comment]
For anyone else stuck in the past like me, `7.1.65` looks like the last supported tag.

**Comment by j0nnymoe** [comment]
To clarify, thats the last working tag but it's something we no longer support (as mentioned in our previous announcements)

**Comment by zimmertr** [comment]
> To clarify, thats the last working tag but it's something we no longer support (as mentioned in our previous announcements)

> For anyone else stuck in the past like me, 7.1.65 **looks like the last supported tag.**
