### ISSUE TITLE
Data is not persistent, auto backups disappear after upgrade. 

### ISSUE THREAD

**Issue by Kiendeleo** [linuxserver/docker-unifi-controller#156]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Using Docker stop, rm, and docker run to upgrade should maintain data.

## Current Behavior
Upon upgrade, all data is wiped and you have to restore from backup

## Steps to Reproduce

1. On a working system, stop and remove docker container
2. perform docker pull to get latest version
3. Execute Docker run 
4.

## Environment
**OS:Ubuntu**
**CPU architecture:** x86_64
**How docker service was installed:**
official repo

## Command used to create docker container (run/create/compose/screenshot)
docker run -d --name Unifi-Controller -e PUID=1000  -e PGID=1000 -v Unifi-Controller-Data-New:/config  --net AdminNet --hostname [controller hostname] --ip 192.168.1.16 --restart unless-stopped linuxserver/unifi-controller

## Docker logs
There are no logs after restart

**Comment by j0nnymoe** [comment]
Are you sure you're not wiping out the docker volume you're using? We have no reports of users running this with folder mappings.

**Comment by Kiendeleo** [comment]
This was a user error on my part, there was an added space at the end of the volume declaration of the storage volume. This made the volume map to ":/config " instead of ":/config" so the config file was being destroyed each time I upgraded. Thank you for your help.
