### ISSUE TITLE
AP are not updating

### ISSUE THREAD

**Issue by HolgerBri** [linuxserver/docker-unifi-controller#157]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
When automatic update is selected all APs should have the latest firmware version

## Current Behavior
My APs have old and different versions: two U6-Lite are on 5.43.14, one U6-Lite has 5.60.13 and U6-Mesh 6.0.4 . Device Auto Update is activated and last check was this morning

## Environment
Network 7.2.92 - official docker container has been updated two days ago
Container is installed on a Synology NAS

**Comment by aptalca** [comment]
This should be reported upstream to unifi. We develop the container, not the app

**Comment by JohnKiller** [comment]
Hi, check the release notes: https://community.ui.com/releases/UniFi-Access-Point-6-2-35/abeb301f-8d9c-4cbe-b246-6fc3f1528a29

> U6-Pro/Mesh needs to be upgraded to [5.67.0 ](https://dl.ui.com/unifi/firmware/UAP6MP/5.67.0.13114/BZ.ipq50xx_5.67.0+13114.210608.1558.bin)first before upgrading to 5.68.0+.
