### ISSUE TITLE
Container no longer runs in Azure Container Instaces

### ISSUE THREAD

**Issue by oradcliffe** [linuxserver/docker-unifi-controller#158]
---
name: Container no longer runs on Azure Container Instances
about: Using lscr.io/linuxserver/unifi-controller:latest, container no longer runs in ACI.  It did work last week.

---
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Container should server up Unifi application

## Current Behavior

Container restarts several times until reaching a threshold, where it sits in terminated state.

## Steps to Reproduce

1. Use lscr.io/linuxserver/unifi-controller:latest as pull source in ACI, GUI or CLI, default settings all around

## Environment
**OS:**
**CPU architecture:** x86_64
**How docker service was installed:**

## Docker logs
 Will work on getting these - need to get to another computer.

**Comment by Roxedus** [comment]
Please follow the issue template

**Comment by oradcliffe** [comment]
Edited.

**Comment by Roxedus** [comment]
No

**Comment by oradcliffe** [comment]
Ok.. is there someone else here who can take a look?  What else do you need?

**Comment by oradcliffe** [comment]
Ok, is there someone that can help?

**Comment by oradcliffe** [comment]
Ok, is there someone that can help?

**Comment by j0nnymoe** [comment]
You've not provided any logs.

**Comment by Blinq-SanderBlom** [comment]
Hi! I think I have the same issue with running the image in a Azure docker Instance. The error I get is `
s6-overlay-suexec: fatal: can only run as pid 1`:

Here is the Terraform code for the infrastructure in Azure:

```
resource "azurerm_container_group" "unifi" {
  name                = "ci-${var.project_name}"
  location            = var.location
  resource_group_name = data.azurerm_resource_group.deployment.name
  ip_address_type     = "Public"
  os_type             = "Linux"

  container {
    name   = "unifi"
    image  = "linuxserver/unifi-controller:latest"
    cpu    = 1
    memory = 2

    ports {
      port     = 3478
      protocol = "UDP"
    }

    ports {
      port     = 10001
      protocol = "UDP"
    }

    ports {
      port     = 8080
      protocol = "TCP"
    }

    ports {
      port     = 8443
      protocol = "TCP"
    }

    ports {
      port     = 8880
      protocol = "TCP"
    }

    environment_variables = {
      PUID = 1000
      PGID = 1000
      TZ   = "CET"
    }

    volume {
      name                 = "unifistorage"
      mount_path           = "/config"
      storage_account_name = azurerm_storage_account.unifi_sa.name
      share_name           = azurerm_storage_share.unifi_share.name
      storage_account_key  = data.azurerm_storage_account.access_key.primary_access_key
    }
  }

  diagnostics {
    log_analytics {
      log_type      = "ContainerInsights"
      workspace_id  = azurerm_log_analytics_workspace.unifi_logs.workspace_id
      workspace_key = azurerm_log_analytics_workspace.unifi_logs.primary_shared_key
      metadata      = null
    }
  }

}
```
