### ISSUE TITLE
Unifi Controller logs in stdout

### ISSUE THREAD

**Issue by keatontaylor** [linuxserver/docker-unifi-controller#16]
It would be nice to have the logging output of the unifi controller service pushed to stdout. This would allow for services like logspout to gather logs about the unif controller service and send them to things like papertrail, Elastic Stack or simply syslog destination.

As it stands right now, the internal logs of the controller are suppressed and not available when running things like docker logs... instead those logs seem to only be for the container itself not the service that it is running.

**Comment by aptalca** [comment]
We don't suppress app logs.

Unifi logs can be found under `/config/logs/`

**Comment by keatontaylor** [comment]
@aptalca, suppressed as in not sent to stdout which would effectively make the unifi logs visible when running `docker logs <container-name>`

**Comment by aptalca** [comment]
Unifi logs to files by default, not stdout

**Comment by j0nnymoe** [comment]
Closing as no response. We have no plans to output application logs to stdout.
