### ISSUE TITLE
Self-Signed Certificate Does Not Contain "Subject Alternative Name" field

### ISSUE THREAD

**Issue by pearson** [linuxserver/docker-unifi-controller#161]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
I expected the container release to generate a self-signed certificate in the same way the official Linux / Windows versions do, in that it would contain a "Subject Alternative Name" field with a value of "DNS Name=UniFi". 

The problem is that under Windows 11, even if self-signed certificates are properly installed in "Trusted Root Certification Authorities", web browsers will show a server's certificate as untrusted if the installed certificate lacks that "Subject Alternative Name" field. Some information regarding this can be found at [this link](https://blog.shafeeque.in/browser-not-trusting-self-signed-certificate-even-after-importing-into-the-trusted-root-certificate-folder/).

For small, local-use-only installs where self-signed certificates are appropriate, a user might wish to install that certificate locally to prevent annoying browser security pop-ups. Invalid certificates also prevent some web browsers from saving usernames and passwords.

## Current Behavior
The self-signed certificate that is generated does not contain a "Subject Alternative Name" field. 

## Steps to Reproduce

1. Spin up a new container
2. Load the UI in a web browser
3. Inspect the certificate
4. Notice the lack of a "Subject Alternative Name" field
5. Export the certificate
6. Under Windows 11, double-click the certificate and import into "Trusted Root Certification Authorities"
7. Add the appropriate entry for the server to `C:\Windows\System32\drivers\etc\hosts`
8. Restart web browsers
9. Open a web browser to the UniFi Network Controller and notice the certificate error
10. Repeat with an official install of the UniFi Network Controller and notice there is no certificate error

## Environment
**OS:** Ubuntu 22.10
**CPU architecture:** x86_64
**How docker service was installed:** `docker pull linuxserver/unifi-controller`

## Command used to create docker container (run/create/compose/screenshot)
Using the `docker-compose.yml` outlined at [hub.docker.com](https://hub.docker.com/r/linuxserver/unifi-controller#:~:text=docker%2Dcompose%20(recommended), changing only the `<path_to_data>`

**Comment by aptalca** [comment]
Honestly, I don't believe self signed certs are ever appropriate (unless for testing) in this day and age. It's super easy to reverse proxy with proper certs even for local only connections.

Check out our SWAG image that works great with unifi.

**Comment by pearson** [comment]
In the setting of a home that has no need for remote access to the UniFi controller, to me it seems like overkill to set up a reverse proxy for the sole purpose of making logging into UniFi a bit more convenient. Everyone has their own opinions of such things, though.

**Comment by aptalca** [comment]
That's fine, but it's not worth our time to update the self signed cert as it takes less than 5 minutes to put it behind SWAG, and once done, it works on all machines on the lan without having to import and trust certs.

You can either set your own cert (validated or self signed) in the unifi gui settings, or customize the container: https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers
