### ISSUE TITLE
[BUG] Wrong Java memory options in 169 release

### ISSUE THREAD

**Issue by amiga23** [linuxserver/docker-unifi-controller#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Invalid maximum heap size: -Xmx1024MM
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

### Steps To Reproduce

Upgrade from 168 to 169

### Environment

```markdown
- OS: manjaro/archlinux ARM64
- How docker service was installed:
k3s
```

### CPU architecture

arm64

### Docker creation

```bash
Kubernetes deployment
```

### Container logs

```bash
This message apears in a loop:

Invalid maximum heap size: -Xmx1024MM
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by amiga23** [comment]
Parameter needs to be set without M now
MEM_LIMIT=1024M -> MEM_LIMIT=1024

**Comment by valentinvieriu** [comment]
@thespad 
I can confirm the same bug. I've double checked and I'm not adding M at the end, I use MEM_LIMIT=1024

**Comment by ints99** [comment]
Why this is closed? The same issue is still not fixed?

**Comment by Roxedus** [comment]
There is nothing to fix, you need to alter your deployment according to our documentation.

**Comment by ints99** [comment]
Ok, thanks, now I see the solution! Thnx!
