### ISSUE TITLE
Let's Encrypt support

### ISSUE THREAD

**Issue by timschwartz** [linuxserver/docker-unifi-controller#17]
Can we get support for Let's encrypt certificates?

**Comment by CHBMB** [comment]
The way we advise this is to stick this container behind our preconfigured [LetsEncrypt container](https://github.com/linuxserver/docker-letsencrypt) as a reverse proxy.

We have [preconfigured config](https://github.com/linuxserver/reverse-proxy-confs) for the unifi controller that are pulled into our LetsEncrypt container.

You can read about this on our [blog.](https://blog.linuxserver.io/2019/04/25/letsencrypt-nginx-starter-guide/)

**Comment by JohnGalt1717** [comment]
It would be much nicer if this was done internally and we could just provide the environment variables to have it point to the lets encrypt pem files like Home Assistant does as an example. Then we don't have to have proxying for something that it can do built in.

**Comment by j0nnymoe** [comment]
It's still abit of a hacky solution using a script like that. It amazes me that they haven't put support for letsencrypt in unifi itself.
Can always try adding it yourself with this https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
