### ISSUE TITLE
After the last update UNIFI controller doesn't works anymore

### ISSUE THREAD

**Issue by surfparadise** [linuxserver/docker-unifi-controller#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error: A fatal exception has occurred. Program will exit.
Invalid initial heap size: -Xms1024MM
Error: Could not create the Java Virtual Machine.

### Steps To Reproduce

......................

### Environment

```markdown
- OS:UNRAID docker
```

### CPU architecture

x86-64

### Docker creation

```bash
GUI UNRAID.
```

### Container logs

```bash
Error: A fatal exception has occurred. Program will exit.
Invalid initial heap size: -Xms1024MM
Error: Could not create the Java Virtual Machine.
```

**Comment by surfparadise** [comment]
Fixed.

changed 
MEM_STARTUP: 1024M

to
MEM_STARTUP: 1024

**Comment by isaac-the-newt** [comment]
Hi there,
My docker image also suffered from the same issue following the last upgrade (less than 24 hours ago).
I have edited the MEM settings as described by surfparadise and the docker is now running again.
Thanks surfparadise. 😘

**Comment by qistoph** [comment]
Thanks @surfparadise!

**Comment by thespad** [comment]
Duplicate of #168

**Comment by 7ooL** [comment]
removing the 'M' also worked for me and my container.

**Comment by vopi61** [comment]
Thx alot, it helpt me to start my container
