### ISSUE TITLE
[BUG] ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by PrisonMike2** [linuxserver/docker-unifi-controller#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When navigating to the ip of my unifi docker (192.168.1.2) I get an error "the site cant be reached" and ERR_CONNECTION_CLOSED at the bottom of the page (using chrome). I am able to ping the docker from my desktop pc.

### Expected Behavior

Open the Unifi application when going to 192.168.1.2

### Steps To Reproduce

open web browser
type 192.168.1.2

### Environment

```markdown
- OS: unraid
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
https://imgur.com/a/ujYPdRr
```

### Container logs

```bash
ErrorWarningSystemArrayLogin


[custom-init] No custom services found, skipping...
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/10-adduser

-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/15-install
*** installing unifi packages ***
Selecting previously unselected package unifi.
(Reading database ... 8895 files and directories currently installed.)
Preparing to unpack /app/unifi.deb ...
Unpacking unifi (7.2.95-18699-1) ...
Setting up unifi (7.2.95-18699-1) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
cont-init: info: /etc/cont-init.d/15-install exited 0
cont-init: info: running /etc/cont-init.d/20-config
*** Setting Java memory limit to 1024 ***
*** Setting Java memory minimum to 1024 ***
cont-init: info: /etc/cont-init.d/20-config exited 0
cont-init: info: running /etc/cont-init.d/30-keygen
cont-init: info: /etc/cont-init.d/30-keygen exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun unifi (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
```

**Comment by condorXI** [comment]
I have the same problem. But my log is also spamming this error after "99-ci-service-check successfully started":

`Invalid maximum heap size: -Xmx1024MM
Error: Could not create the Java Virtual Machine.
`

**Comment by encg** [comment]
For WebUI, you have `https://192.168.1.2:[PORT:8443]`

Is that right or should it just be `https://192.168.1.2:8443`?

**Comment by PrisonMike2** [comment]
> For WebUI, you have `https://192.168.1.2:[PORT:8443]`
> 
> Is that right or should it just be `https://192.168.1.2:8443`?

Hello, I have tried to change the WebUI to https://192.168.1.2:8443

After I changed it, the problem is still the same. I had it set to https://192.168.1.2:[PORT:8443] because I posted the same issue on the unraid support form and someone advised me to change the WebUI to https://192.168.1.2:[PORT:8443] and it didn't work either.

Here is a paste of my docker log [Pastebin](https://pastebin.com/g5N0Cvqn)

I appreciate any help that anyone can provide.

**Comment by encg** [comment]
Do you have a firewall enabled that could be blocking the port?

**Comment by PrisonMike2** [comment]
> Do you have a firewall enabled that could be blocking the port?

I dont have any firewalls on my network

**Comment by PrisonMike2** [comment]
Hello all, I am now getting a new error in my logs when I try to start the container. 

 

[Please see my pastebin link for the logs](https://pastebin.com/a5jneCt5)

**Comment by PrisonMike2** [comment]
Not sure what the issue ended up being. I gave up and bought a Unifi Dream Machine Pro. Issue closed.
