### ISSUE TITLE
Invalid initial heap size: -Xms1024MM  Error: Could not create the Java Virtual Machine.  Error: A fatal exception has occurred. Program will exit.

### ISSUE THREAD

**Issue by patchinswayze** [linuxserver/docker-unifi-controller#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Docker container fails to start with error code Invalid initial heap size: -Xms1024MM

Error: Could not create the Java Virtual Machine.

Error: A fatal exception has occurred. Program will exit.

### Expected Behavior

Docker container should start

### Steps To Reproduce

updated to Latest version tag from [7.2.95-ls166]

### Environment

```markdown
- OS: Debian 11
- How docker service was installed: apt-get install docker
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d \
  --name=unifi-controller \
  --hostname=unifi-controller \
  -e PUID=1000 \
  -e PGID=1000 \
  -e MEM_LIMIT=1024M `#optional` \
  -e MEM_STARTUP=1024M `#optional` \
  -p 3478:3478/udp \
  -p 10001:10001/udp \
  -p 8080:8080 \
  -p 8443:8443 \
  -p 1900:1900/udp `#optional` \
  -p 8843:8843 `#optional` \
  -p 8880:8880 `#optional` \
  -p 6789:6789 `#optional` \
  -p 5514:5514/udp `#optional` \
  -v /var/docker/unify:/config \
  --restart always \
  ghcr.io/linuxserver/unifi-controller:latest
```

### Container logs

```bash
Invalid initial heap size: -Xms1024MM

Error: Could not create the Java Virtual Machine.

Error: A fatal exception has occurred. Program will exit.

Invalid initial heap size: -Xms1024MM

Error: Could not create the Java Virtual Machine.

Error: A fatal exception has occurred. Program will exit.

Invalid initial heap size: -Xms1024MM

Error: Could not create the Java Virtual Machine.

Error: A fatal exception has occurred. Program will exit.
```

**Comment by Roxedus** [comment]
Dupe of #168

**Comment by patchinswayze** [comment]
I have since rolled back to 7.2.95-ls166 so this isn't an urgent issue, but I would like to be running the latest version of Unifi controller to avoid any security issues. I suspect the issue is related to Unifi changing from Java 8 to 11, but not sure why I am the only one having issues
