### ISSUE TITLE
[FEAT] version bump to v7.3.81

### ISSUE THREAD

**Issue by StayPirate** [linuxserver/docker-unifi-controller#187]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

On January 10th 2023 a new version [was released](https://community.ui.com/releases/UniFi-Network-Application-7-3-81/d1b49ec9-8ea6-4ca5-bf45-9e6a22cfa895).

How does the version bump is triggered for this container? Does it require manual steps?

### Reason for change

The reason for this request is to keep the container up-to-date with the latest release available. Fortunately this time there are no security fixes, but for future releases will be important to timely get the latest updates in case a vulnerability is fixed and so made public.

**Comment by Roxedus** [comment]
We have the latest stable release pushed, as we are automatically checking their apt repo multiple times a day. 
You linked a release candidate.

**Comment by StayPirate** [comment]
You are right, I didn't notice that. Thanks for the explanation.

**Comment by StayPirate** [comment]
FYI, since 30/1/2023 [v7.3.83](https://community.ui.com/releases/UniFi-Network-Application-7-3-83/88f5ff3f-4c13-45e2-b57e-ad04b4140528) is available.

**Comment by thespad** [comment]
They only updated their apt repo about 4 hours ago, and there are issues with the Ubuntu mirror infrastructure that are preventing us from building it at the moment.
