### ISSUE TITLE
[FEAT] Expose MongoDB

### ISSUE THREAD

**Issue by JonnyTech** [linuxserver/docker-unifi-controller#192]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Expose the MongoDB (port 27117) outside the container

### Reason for change

I have a utility to grab device info and display it remotely, but have been unable to access it.

### Proposed code change

Have tried adding`-p 27117 27117` and `-expose 27117` but not sure what else can work.

**Comment by thespad** [comment]
The unifi controller software manages the mongo database process and AFAIK it only binds to a local socket, not to a TCP port, so there's no way to expose it outside the container.

**Comment by JonnyTech** [comment]
Ah, that explains it. Thanks for the detail. I am a docker newbie, is there any way to forward that "local" port by any other means?

**Comment by Roxedus** [comment]
There is no port to expose.
