### ISSUE TITLE
launching with Xmx1024M may override user preferences in data system.properties

### ISSUE THREAD

**Issue by bagobones** [linuxserver/docker-unifi-controller#2]
5.6.20 of unifi and higher may use more memory by default, there is a recommended way to change this in the system.properties file however the docker image forces a launch with Xmx1024M

I would recommend replacing this with environment variables for xms and xmx or simply remove the Xmx1024M parameter from the startup run command.

This can be a problem on SMALL VPS instances or Raspberry pi systems with only 1 GB of memory for everything.

https://community.ubnt.com/t5/UniFi-Wireless/NOTICE-UniFi-Controller-Memory-Usage-5-6-20/td-p/2137209

**Comment by dg-jrichardson** [comment]
I agree, this could be an issue for RPi users. I did some real quick testing and I think it would be easy enough to set an ENV in the Dockerfile to the amount of memory to allocate and update root/etc/services.d/unifi/run to start ace.jar with that. If you want I can submit a PR, @j0nnymoe

**Comment by teknofile** [comment]
I agree, this could be an issue for RPi users. I did some real quick testing and I think it would be easy enough to set an ENV in the Dockerfile to the amount of memory to allocate and update root/etc/services.d/unifi/run to start ace.jar with that. If you want I can submit a PR, @j0nnymoe
