### ISSUE TITLE
How does this project differ from jacobalberty/unifi-docker

### ISSUE THREAD

**Issue by mafrosis** [linuxserver/docker-unifi-controller#20]
I'm adopting Unifi at home, and there appear to be two similar competing projects for the Unifi controller software in Docker. 

How does this project differ from https://github.com/jacobalberty/unifi-docker ?

Both projects started around 2015, the other one has seen a little more activity, but that doesn't necessarily mean much. A comparison in your README would be very useful for new incoming people.

Thanks!

**Comment by aptalca** [comment]
There is no competition. We just make images for things that we use, and then share them with the community and support them.

Feel free to try both and take your pick.

**Comment by mafrosis** [comment]
Sure.. Perhaps the word “competing” set the wrong impression here.

**Comment by mbiebl** [comment]
Hi, I'm in the same situation here. I'm new to the Unifi world and about to setup a controller.
Would be nice to know, how those two docker images differ. This would help me to chose.

**Comment by mbiebl** [comment]
A few bits I noticed while only glancing at it superficially:
- linuxserver/unifi-controller seems to use s6 inside docker
- jacobalberty/unifi uses a shell script

- linuxserver/unifi-controller runs the server under a dedicated uid/gid, jacobalberty/unifi uses root by default (although it can be configured via the RUNAS_UID0 key).

**Comment by CHBMB** [comment]
Never heard of the other image.  I'd be surprised if it has the infrastructure and team behind it as we do, but you gotta make the decision for yourself.
