### ISSUE TITLE
[BUG] 7.3.83, UI unreachable on Synology host w / -v 

### ISSUE THREAD

**Issue by crl0wryjr** [linuxserver/docker-unifi-controller#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unifi controller does not start up completely / successfully:  UI unavailable

from webbrowser

> Hmmm… can't reach this page unifi.evilroy.org refused to connect.
> Try:
> 
> Checking the connection
> [Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
> ERR_CONNECTION_REFUSED
> 

from Curl

> curl localhost:8443
> curl: (7) Failed to connect to localhost port 8443 after 0 ms: Connection refused
> 

### Expected Behavior

The UI comes up when I navigate to it

from Web browser

> Step 1 of 6
> Name Your Network application
> Use a simple name to help differentiate your Network application when managing multiple networks.
> Network application Name
> UniFi Network
> 
> By selecting this you are agreeing to [end user license agreement](https://www.ui.com/eula/) and the [terms of service](https://www.ui.com/legal/termsofservice/).
> Or restore setup from backup
> 

from Curl
> curl localhost:8443
> Bad Request
> This combination of host and port requires TLS.

### Steps To Reproduce

Was working prior to 7.3.8 - stopped working after updated
Host is a Synology

Docker Compose
>   unifi-controller:
>     image: lscr.io/linuxserver/unifi-controller
>     container_name: unifi-frmCompose
>     hostname: unifi.evilroy.org
>     restart: unless-stopped
>     networks:
>       - synbridge
>     volumes:
>       - /volume1/VirtualEnvironments/Unifi/config:/config
>       - /usr/share/zoneinfo/US:/usr/share/zoneinfo/US:ro
>       - /usr/syno/etc/certificate/system/default:/usr/syno/ssl:ro
>     ports:
>       - 3478:3478/udp
>       - 10001:10001/udp
>       - 8080:8080
>       - 8443:8443
>       # - 1900:1900/udp #optional
>       - 8843:8843 #optional
>       - 8880:8880 #optional
>       - 6789:6789 #optional
>       - 5514:5514/udp #optional
>     environment:
>       - TZ=US/Eastern
>       - PUID=1026
>       - PGID=100
>     labels:
>       - "com.centurylinklabs.watchtower.enable=true"

Output from log file

> docker logs unifi-frmCompose
> [migrations] started
> [migrations] no migrations found
> ───────────────────────────────────────
> 
>       ██╗     ███████╗██╗ ██████╗
>       ██║     ██╔════╝██║██╔═══██╗
>       ██║     ███████╗██║██║   ██║
>       ██║     ╚════██║██║██║   ██║
>       ███████╗███████║██║╚██████╔╝
>       ╚══════╝╚══════╝╚═╝ ╚═════╝
> 
>    Brought to you by linuxserver.io
> ───────────────────────────────────────
> 
> To support LSIO projects visit:
> https://www.linuxserver.io/donate/
> 
> ───────────────────────────────────────
> GID/UID
> ───────────────────────────────────────
> 
> User UID:    1026
> User GID:    100
> ───────────────────────────────────────
> 
> [custom-init] No custom files found, skipping...
> WARN Unable to load properties from '/usr/lib/unifi/data/system.properties' - /usr/lib/unifi/data/system.properties (Permission denied)
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.59.jar) to field java.io.ObjectStreamClass$Caches.localDescs
> WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

Noticing the warning about permissions to /usr/lib/unifi/data/system. Properties I tried running docker-compose without volume mount to /config, and everything worked
>     volumes:
>      # - /volume1/VirtualEnvironments/Unifi/config:/config

I have confirmed all dirs / files are owned by me

> id
> uid=1026(crl0wryjr) gid=100(users) groups=100(users),101(administrators),65538(docker)

> ls -alR
> .:
> total 16
> drwxrwxrwx+  3 root      root  4096 Mar 20 17:56 .
> drwxrwxrwx+ 15 root      root  4096 Mar 21 10:53 ..
> drwxrwxrwx+  5 crl0wryjr users 4096 Mar 21 11:50 config
> 
> ./config:
> total 20
> drwxrwxrwx+ 5 crl0wryjr users 4096 Mar 21 11:50 .
> drwxrwxrwx+ 3 root      root  4096 Mar 20 17:56 ..
> drwxrwxrwx+ 2 crl0wryjr users 4096 Mar 21 11:50 data
> drwxrwxrwx+ 2 crl0wryjr users 4096 Mar 21 11:50 logs
> drwxrwxrwx+ 2 crl0wryjr users 4096 Mar 21 11:50 run
> 
> ./config/data:
> total 20
> drwxrwxrwx+ 2 crl0wryjr users 4096 Mar 21 11:50 .
> drwxrwxrwx+ 5 crl0wryjr users 4096 Mar 21 11:50 ..
> -rwxrwxrwx+ 1 crl0wryjr users 4230 Mar 21 11:50 keystore
> -rwxrwxrwx+ 1 crl0wryjr users 1132 Mar 21 11:50 system.properties
> 
> ./config/logs:
> total 8
> drwxrwxrwx+ 2 crl0wryjr users 4096 Mar 21 11:50 .
> drwxrwxrwx+ 5 crl0wryjr users 4096 Mar 21 11:50 ..
> 
> ./config/run:
> total 8
> drwxrwxrwx+ 2 crl0wryjr users 4096 Mar 21 11:50 .
> drwxrwxrwx+ 5 crl0wryjr users 4096 Mar 21 11:50 ..

### Environment

```markdown
Synology
```

### CPU architecture

x86-64

### Docker creation

```bash
Docker Compose
>   #############
>   #
>   # Unifi Controller SW
>   #
>   #############
>   # To Do:
>   #
>   #
>   unifi-controller:
>     image: lscr.io/linuxserver/unifi-controller
>     container_name: unifi-frmCompose
>     hostname: unifi.evilroy.org
>     restart: unless-stopped
>     networks:
>       - synbridge
>     volumes:
>       - /volume1/VirtualEnvironments/Unifi/config:/config
>       - /usr/share/zoneinfo/US:/usr/share/zoneinfo/US:ro
>       - /usr/syno/etc/certificate/system/default:/usr/syno/ssl:ro
>     ports:
>       - 3478:3478/udp
>       - 10001:10001/udp
>       - 8080:8080
>       - 8443:8443
>       # - 1900:1900/udp #optional
>       - 8843:8843 #optional
>       - 8880:8880 #optional
>       - 6789:6789 #optional
>       - 5514:5514/udp #optional
>     environment:
>       - TZ=US/Eastern
>       - PUID=1026
>       - PGID=100
>     labels:
>       - "com.centurylinklabs.watchtower.enable=true"
```

### Container logs

```bash
docker logs unifi-frmCompose
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1026
User GID:    100
───────────────────────────────────────

[custom-init] No custom files found, skipping...
WARN Unable to load properties from '/usr/lib/unifi/data/system.properties' - /usr/lib/unifi/data/system.properties (Permission denied)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.59.jar) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by crl0wryjr** [comment]
> Everything isn't owned by you, it's owned by a Synology ACL. You need to explicitly add the user account you're running the container as to the folder permissions.

Please clarify ...

My uid is 1026 and my gid is 100 

> id
> uid=1026(crl0wryjr) gid=100(users) groups=100(users),101(administrators),65538(docker)

In my docker-compose I start the container with uid 1026 and gid 100
>     environment:
>       - TZ=US/Eastern
>       - PUID=1026
>       - PGID=100

In the Unifi logs it shows UID 1026 and GIG 100

> To support LSIO projects visit:
> https://www.linuxserver.io/donate/
> 
> ───────────────────────────────────────
> GID/UID
> ───────────────────────────────────────
> 
> User UID:    1026
> User GID:    100
> ───────────────────────────────────────

and doing an ls -al shows all the files and folders owned by my uid/gid

> total 16
> drwxrwxrwx+ 3 root root 4096 Mar 20 17:56 .
> drwxrwxrwx+ 15 root root 4096 Mar 21 10:53 ..
> drwxrwxrwx+ 5 crl0wryjr users 4096 Mar 21 11:50 config
> 
> ./config:
> total 20
> drwxrwxrwx+ 5 crl0wryjr users 4096 Mar 21 11:50 .
> drwxrwxrwx+ 3 root root 4096 Mar 20 17:56 ..
> drwxrwxrwx+ 2 crl0wryjr users 4096 Mar 21 11:50 data
> drwxrwxrwx+ 2 crl0wryjr users 4096 Mar 21 11:50 logs
> drwxrwxrwx+ 2 crl0wryjr users 4096 Mar 21 11:50 run
> 
> ./config/data:
> total 20
> drwxrwxrwx+ 2 crl0wryjr users 4096 Mar 21 11:50 .
> drwxrwxrwx+ 5 crl0wryjr users 4096 Mar 21 11:50 ..
> -rwxrwxrwx+ 1 crl0wryjr users 4230 Mar 21 11:50 keystore
> -rwxrwxrwx+ 1 crl0wryjr users 1132 Mar 21 11:50 system.properties
> 
> ./config/logs:
> total 8
> drwxrwxrwx+ 2 crl0wryjr users 4096 Mar 21 11:50 .
> drwxrwxrwx+ 5 crl0wryjr users 4096 Mar 21 11:50 ..
> 
> ./config/run:
> total 8
> drwxrwxrwx+ 2 crl0wryjr users 4096 Mar 21 11:50 .
> drwxrwxrwx+ 5 crl0wryjr users 4096 Mar 21 11:50 .

This had been working for nearly a year, and only stopped working with 7.3.8.
What am I missing?

**Comment by thespad** [comment]
You need to make sure that `synoacltool -get /volume1/VirtualEnvironments/Unifi/config` includes your `crl0wryjr` user as an explicit entry.

If it does, please post your server.log and mongod.log from /config/logs (probably sensible to delete/rename any existing log and restart the container to minimise noise).

**Comment by crl0wryjr** [comment]
I am listed as Owner:

> synoacltool -get /volume1/VirtualEnvironments/Unifi/config/
> ACL version: 1
> Archive: is_inherit,is_support_ACL
> Owner: [crl0wryjr(user)]
> ---------------------
>          [0] group:administrators:allow:rwxpdDaARWc--:fd-- (level:2)
>          [1] group::allow:rwxpdDaARWc--:fd-- (level:2)


This is consistent with the other images/containers I'm running.

As a lark, I changed by GID in docker-compose to 101 (administrators) and it works now - but not really a surprise.
If I exec into the container I see all the files are owned by abc:abc with a uid of 1026 and a gid of 101 (was 100)
>  id abc
> uid=1026(abc) gid=101(abc) groups=101(abc),100(users)

**Comment by crl0wryjr** [comment]
Well, I scanned through my docker-compose file and noticed that I have set my gid to 101 for a couple other containers (4 of the 16 I'm running), which tells me I've bumped into permission problems in the past and solved them with a gid of 101 (administrators).

**Comment by thespad** [comment]
I return to my original point. In order for Synology ACL permissions to work correctly with Docker containers, the user (or primary group) must be added *explicitly* to the ACL. Inherited permissions via group membership etc. are not sufficient.

**Comment by crl0wryjr** [comment]
Not that it matters at this point, but I don't think you're correct, or you're not explaining it correctly.
It works now ***because*** I changed my group ID. I changed nothing in the ACL.

> you wrote:   Inherited permissions via group membership etc. are not `sufficient.`

Regardless, you got me in the right direction, and I'm working again. Thanks
