### ISSUE TITLE
[Docs] Please provide details on how to use the "mongoless" image

### ISSUE THREAD

**Issue by ItalyPaleAle** [linuxserver/docker-unifi-controller#205]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I am very interested in the "mongoless" images that were introduced in #196 . However, I am not able to find some documentation on how to use those.

### Reason for change

There are no docs for the feature and it's unclear to me how to use those images.

**Comment by j0nnymoe** [comment]
I guess you didn't look at the actual branch? https://github.com/linuxserver/docker-unifi-controller/tree/mongoless

**Comment by ItalyPaleAle** [comment]
Thanks, I did not realize the docs were in a separate branch.

I can open a PR to link to that branch in the main one if that works for you.
