### ISSUE TITLE
[BUG] First time setup -- HTTP Status 404 – Not Found

### ISSUE THREAD

**Issue by C0nvictions** [linuxserver/docker-unifi-controller#206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I go to webUI, I get the error in the title

### Expected Behavior

I should actually be able to access the webUI

### Steps To Reproduce

1. Install docker
2. click webUI

### Environment

```markdown
Unraid docker
```

### CPU architecture

x86-64

### Docker creation

```bash
I didn't use one -- I added through unraid.
```

### Container logs

```bash
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.59.jar) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

*** Setting Java memory limit to 1024 ***
*** Setting Java memory minimum to 1024 ***
[custom-init] No custom files found, skipping...
```

**Comment by AnakinFoxe** [comment]
I think it is because the container takes very long to initialize (which happens to me as well). You should see a line `[ls.io-init] done.` in the end when the initialization is complete.

**Comment by enzops** [comment]
I have the same issue since weeks with the latest image through unraid.

The service doesn't start with an error : logger: socket /dev/log: No such file or directory

**Comment by C0nvictions** [comment]
I ended up posting in the discord and got an answer that helped me resolve the error:

![Screenshot_20230430_115129_Discord](https://user-images.githubusercontent.com/81660340/235371149-32aff93d-1cbe-46d4-8191-75ee238cbc9b.jpg)

**Comment by enzops** [comment]
Thanks for the tips.

I've changed the path to an new folder (you can let it in the appdata folder), and restored an autobackup from the old container folder.

Thanks to the autobackup

**Comment by piazza702** [comment]
For anyone coming across this in the future. I was able to resolve it but leaving the variables MEM_LIMIT and MEM_STARTUP blank.
