### ISSUE TITLE
Edit unifi.http.port to avoid manually adoption when using port 8080 on the same host

### ISSUE THREAD

**Issue by M0NsTeRRR** [linuxserver/docker-unifi-controller#21]
Hey, first of all thanks you for your work.

I'm running the container behind traefik on the same host as traefik (traefik use port 8080). It would be cool if we can pass an environment variable to change `unifi.http.port` in `system.properties` file to avoid manually adoption at each adoption of UAP.

**Comment by zaggash** [comment]
Maybe easier to change traefik port 8080.
Better, iir 8080 is used for the management plane, so you can remove 8080 from the ingress and use it as a backend through https traefik frontend.

**Comment by M0NsTeRRR** [comment]
I use port 8080 on Traefik to get metrics for my monitoring and I prefer to keep this port to this usage.

**Comment by zaggash** [comment]
I understand.
Be careful, in traefik 2.0 its another story.
There is no more port 8080 unless you use another riuter for the api.

That being said, its up to you.

**Comment by M0NsTeRRR** [comment]
Thanks for the advices :)

**Comment by aptalca** [comment]
You can map port 8080 to whatever you like and then set that address via `set-inform http://$address:PORT/inform`
