### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by JGNi** [linuxserver/docker-unifi-controller#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.59.jar) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[migrations] started
[migrations] no migrations found

### Expected Behavior

Don't know if it has any relevans for the function of it?

### Steps To Reproduce

Install it, changed mobile log to 6780, opened logs

### Environment

```markdown
- OS: unRAID -> Docker
- How docker service was installed:
in unRAID
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='unifi-controller'
  --net='bridge'
  -e TZ="Europe/Paris"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Vader"
  -e HOST_CONTAINERNAME="unifi-controller"
  -e 'MEM_LIMIT'='1024'
  -e 'MEM_STARTUP'='1024'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='https://[IP]:[PORT:8443]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/unifi-controller-logo.png'
  -p '8443:8443/tcp'
  -p '3478:3478/udp'
  -p '10001:10001/udp'
  -p '8080:8080/tcp'
  -p '1900:1900/udp'
  -p '8843:8843/tcp'
  -p '8880:8880/tcp'
  -p '6780:6789/tcp'
  -p '5514:5514/udp'
  -v '/mnt/user/appdata/unifi-controller':'/config':'rw' 'lscr.io/linuxserver/unifi-controller:latest'
66e683de6a2f05d77dafb96cbe988baa44b5961a068f1c5d5aad348861c35d67

The command finished successfully!
```

### Container logs

```bash
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/usr/lib/unifi/lib/tomcat-embed-core-9.0.59.jar) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

*** Setting Java memory limit to 1024 ***
*** Setting Java memory minimum to 1024 ***
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by isaac-the-newt** [comment]
Hi, I see the same issue appearing in my logs after upgrading the Docker container under unRaid 6.11.5. I have also lost the web GUI interface too on port 8443. Multiple restarts of the container have not changed anything.

**Comment by JGNi** [comment]
> ....under unRaid 6.11.5. 

Yup. Same version here. Just upgraded the package to the newest. till the same.

**Comment by thespad** [comment]
This is not a container issue, it's an issue with the Unifi controller software which Ubiquiti need to pull their finger out and fix.

**Comment by nwithan8** [comment]
Issue still exists in latest as of Aug. 14 (7.4.162). Connection refused on attempt to access web UI.
