### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by congkai88** [linuxserver/docker-unifi-controller#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Network 7.4.156 should have OpenVPN in Settings > Left menu as shown in https://youtu.be/ji0nP-QKo3g?t=130. 

However this release cant find the menu

### Expected Behavior

Network 7.4.156 should have OpenVPN in Settings > Left menu as shown in https://youtu.be/ji0nP-QKo3g?t=130. 

### Steps To Reproduce

Network 7.4.156

### Environment

```markdown
- OS:Synology Nas Docker
- How docker service was installed: docker with direct docker image pull
```

### CPU architecture

x86-64

### Docker creation

```bash
Network 7.4.156
```

### Container logs

```bash
-
```

**Comment by j0nnymoe** [comment]
We just pull the packages directly from unifi. I doubt there is little we can do.
