### ISSUE TITLE
[BUG] Problem with UNIFI Network Controller (Docker) in UNRAID

### ISSUE THREAD

**Issue by ANAZHTHTHS** [linuxserver/docker-unifi-controller#214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I am doing a change (e.g. on Firewall Rules) in the "Unifi Device" menu it is adopting again the USG and the Switch and it is not getting to online. It is more common to go back to ofline. The only way to be again online is to SSH the device and give an IP inform (e.g. set-inform http://x.x.x.x:8080/inform) [the x.x.x.x. is the ip of the device].

### Expected Behavior

It should go to "Getting Ready" and then "online". Not "Adoptin" and then "ofline".

### Steps To Reproduce

(not needed)

### Environment

```markdown
- OS: UNRAID 6.11.5 (stable)
- ocker service was installed: throught APPS in the UNRAID APP store (docker version is 20.10..21)
```

### CPU architecture

x86-64

### Docker creation

```bash
(not needed)
```

### Container logs

```bash
There is no problem in LOG. It is reporting nothing as error.
```

**Comment by j0nnymoe** [comment]
Are you overriding the network controller address within unifi?

**Comment by ANAZHTHTHS** [comment]
I have the same ip for UNRAID OS and UNIFI but the ports are ok? I am sorry if I don't understand because I am new in networking.

**Comment by j0nnymoe** [comment]
It's mentioned in our readme but it's a function of unifi itself. As in bridge mode it will be trying to broadcast the container ip rather than the host IP. Look in your unifi settings for that option.

**Comment by ANAZHTHTHS** [comment]
Thank you for your response. It was under Settings -> System -> Host inform and the ip was an other one. I've used the correct one and now it seems that works. Thank you again.
