### ISSUE TITLE
[FEAT] Environment Variable to update inform address

### ISSUE THREAD

**Issue by ja2ui0** [linuxserver/docker-unifi-controller#217]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I want the ability to declare the inform IP / resolvable name in the compose file. If set, that address should enable and populate (and overwrite anything set) the Inform Host Override in Advanced system settings.

### Reason for change

Every docker deployment that isn't using "host" networking will fail to adopt devices on the automatic "inform" interface, as it is configured using an internal docker bridge address. The user who has not been through this before will not know that. Users coming from a cloud key may not be aware, or even need to be, that this option exists. It can take a good amount of time researching the problem to discover what is ultimately a very easy fix within the interface.

Providing an environment variable to override the default behavior, and explaining what it does, will make the user aware of the potential issue even before the first deployment (presuming they read the doc) and save untold amounts of time for potentially innumerable users.

**Comment by aptalca** [comment]
2 separate ways of accomplishing that are explained in the readme.
