### ISSUE TITLE
[FEAT] build with only "released" network applications from unifi

### ISSUE THREAD

**Issue by justsomeguyontheinternet** [linuxserver/docker-unifi-controller#224]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

the current container image is built with the _latest_ available unifi application, but this application is only a "release candidate". my proposal would be to only build the container with the most recent "official" release. if some people want the most recent release candidate, i would propose a separate docker tag for this.

### Reason for change

more stability

**Comment by aptalca** [comment]
We pull the latest version from their stable apt repo. If unifi published a release candidate in their stable apt repo, there is nothing we can do. You'd need to take it up with them.

https://github.com/linuxserver/docker-unifi-controller/blob/master/jenkins-vars.yml#L6

**Comment by justsomeguyontheinternet** [comment]
thanks for the quick feedback; i agree.
