### ISSUE TITLE
[FEAT] Unifi OS

### ISSUE THREAD

**Issue by Curium1** [linuxserver/docker-unifi-controller#225]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hi,
Is it possible to install the Unifi Protect application with this build?

### Reason for change

cant find any documentation about this feature

**Comment by aptalca** [comment]
I believe unifi protect only runs on unifi hardware

**Comment by j0nnymoe** [comment]
They do not offer binaries to allow for selfhosting.
