### ISSUE TITLE
[FEAT] Include MongoDb container in docker-compose so it's a one-step setup 

### ISSUE THREAD

**Issue by rekcodocker** [linuxserver/docker-unifi-controller#226]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I just read that for the new setup, you have to install and maintain/update your own separate MongoDB container. 

I'd really like a one-stop solution and not having to install a separate, manually maintained databasecontainer.

### Reason for change

While I can probably read up on it and get it to work...

I appreciate docker and especially Linuxserver for the simplicity of the setup.

Docker is like "You don't need to install different software + dependencies on your system, just run them isolated in a container".
Linuxserver is like "And here's the container to do it"

Now I have to learn to install a MongoDB, find the right ports, find out how to create a database, maintain it, update it ... 
I don't know if it's against the philosophy of Linuxserver to provide a couple of containers that work together, but I really appreciate the one-stop-show it offers.

### Proposed code change

I think it has to be in a docker - compose so you can have multiple containers managed in one setup file.

**Comment by thespad** [comment]
There's no way for us to make it a one-step setup. Regardless of what we include in the compose it requires user intervention to configure the database as the unifi network application won't do it for you.

The versioning of mongodb in any example would also be difficult due to the gap between versions formally supported by Ubiquiti, versions formally supported by mongo, and versions that actually work with the unifi software.

**Comment by drizuid** [comment]
For the reasons provided by Spad, we will not be supporting this any longer. users are welcome to continue using this container (which has mongodb included) for as long as they like. Support for that mongo version ends in February, 2024. At this time, this container will be deprecated and no longer updated, but will continue to work (without future security updates/patches or application updates)
