### ISSUE TITLE
Immortal container setup - delete all Mongodb setup files feature request

### ISSUE THREAD

**Issue by Rasbat** [linuxserver/docker-unifi-controller#227]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hi, I have run into this issue after controller migration (from one server to another). Can't find sollution.
Clean deployment using docker file on new system > corrupted database after migration (unifi bug) > password issue (fixed) > no web-gui after login >container removed + files deleted > new deployment with clean pulled image
New deployed container is already filled with corrupted database - no web-gui, no way to purge everything and start from clean install and re-migrate unifi setup. Mongo db is somehow filled with some of the data from faulty migration procedure.
Would be very helpfull to have a guidelines or feature to delete all corrupted links/tables to Mongodb or to delete all Mongo files (looks some are outside the container?) to reach clean install/container.

### Reason for change

Can't re-deploy fresh install container

**Comment by thespad** [comment]
All of the database files and config are stored in the /config, along with the application data, so it doesn't matter how many times you pull a new image if you're pointing to the same folder you're going to be using the same data.

The way to start fresh is with a clean /config mount, and then restore a backup during the setup wizard.
