### ISSUE TITLE
[BUG] Fleet documentation for the unifi image is incorrect

### ISSUE THREAD

**Issue by marcaurele** [linuxserver/docker-unifi-controller#230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The documentation on https://fleet.linuxserver.io/image?name=linuxserver/unifi-controller on the container info tab describes the environment variable `MEM_LIMIT` with a value containing a suffix `M` which is incorrect. It must be an integer value describing the value in MB, as correctly described on https://docs.linuxserver.io/images/docker-unifi-controller/#from-2024-01-01-this-image-will-be-deprecated-and-it-will-no-longer-be-updated-please-migrate-to-our-unifi-network-application-image-instead, or on the README of the repository (https://github.com/linuxserver/docker-unifi-controller).

I haven't seen where the documentation of the fleet page is maintained, so I have o idea where I could have push a PR to change the documentation.

### Expected Behavior

Be correctly documented without the unit character:
```
    environment:
      - PUID=1000 # for UserID
      - PGID=1000 # for GroupID
      - MEM_LIMIT=1024 # Optionally change the Java memory limit (-Xmx) (default is 1024M).
```

### Steps To Reproduce

Set the value as described in the doc for the environment variable: `MEM_LIMIT=1024M`.

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
N/A
```

### Container logs

```bash
Invalid maximum heap size: -Xmx1024MM
```

**Comment by drizuid** [comment]
thank you for opening this. unifi-controller will be deprecated in 3 days, so we won't fix this but still appreciate you pointing it out!
