### ISSUE TITLE
Unifi controller version 5.11

### ISSUE THREAD

**Issue by balajeek** [linuxserver/docker-unifi-controller#26]
Will there be an update of unifi-controller 5.11 in this docker?

**Comment by thelamer** [comment]
The latest tag is 5.11.x

**Comment by balajeek** [comment]
Did i request in wrong format or something, its says closed and message 5 hours ago that says "the latest tag is 5.11", does this mean it was updated or it was already 5.11.
but when i do docker pull it says Image is up to date for linuxserver/unifi:latest

Sorry i am new to git hub and practice.

**Comment by thelamer** [comment]
We have been on 5.11.x since September https://github.com/linuxserver/docker-unifi-controller/releases/tag/5.11.39-ls33 the most current release is 5.11.50.

**Comment by balajeek** [comment]
wait a sec, is there another one called linuxserver/unifi instead of linuxserver/unifi-controller?

Just looked in my docker compose file and it says 
hostname: unifi
image: linuxserver/unifi:latest

Also thanks so much for super fast response.

**Comment by balajeek** [comment]
I followed this article installing unifi on my ubuntu docker

https://www.smarthomebeginner.com/install-unifi-controller-on-docker/

**Comment by j0nnymoe** [comment]
They need to update their guide ;-)

**Comment by balajeek** [comment]
so if i switch the line to below it should work and pull the latest, will i loose any settings?

image: linuxserver/unifi-controller:latest 

Sorry again I am new to Docker as well and learning
