### ISSUE TITLE
spamming releases

### ISSUE THREAD

**Issue by ssbarnea** [linuxserver/docker-unifi-controller#32]
Apparently there is a CI tog preoducing releases.... far too often. This is spamming anyone that dared to watch the project for new releases. 

Please assure that a new release does not happen when someone corrects a typo ;)

**Comment by aptalca** [comment]
There will be a new release every time one of the following happens:
1) commit to master (or relevant production) branch
2) OS package update (checked weekly)
3) New upstream app version

That is how our Jenkins automation is currently set up. Feel free to submit PRs for any modifications.

Here's our Jenkins: https://ci.linuxserver.io
Here's the code for our jenkinsfile generator: https://github.com/linuxserver/docker-jenkins-builder
And here's detailed info on how it all comes together: https://github.com/linuxserver/pipeline-triggers
