### ISSUE TITLE
Actual data location 

### ISSUE THREAD

**Issue by icarus747** [linuxserver/docker-unifi-controller#33]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------
Might want to indicate the actual data location for unifi under /usr/lib/unifi/data
There you will find the autobackups and site data.  Useful for keeping a 'local' backup out of the container as well as any persistent configs for the USG like openVPN.

Problem was after an upgrade to the latest image the unifi controller no longer recognized the files under /config and required a restore to change to the new version.  In other words it started the container as if as if it was the first time. 

```
docker exec unifi-controller ls -l /usr/lib/unifi/data
drwxr-xr-x 3 abc abc  4096 Jan 30 04:55 backup
lrwxrwxrwx 1 abc abc    12 Jan 30 04:55 data -> /config/data
drwxr-xr-x 4 abc abc 20480 Jan 30 05:17 db
-rw-r--r-- 1 abc abc 12409 Jan 30 04:58 firmware.json
-rw-r--r-- 1 abc abc  2225 Jan 30 04:56 keystore
drwxr-xr-x 3 abc abc  4096 Jan 30 04:51 sites
-rw-r--r-- 1 abc abc  1339 Jan 30 04:57 system.properties
-rw-r--r-- 1 abc abc  1339 Jan 30 04:57 system.properties.bk
```

## Environment
**OS:** Ubuntu server bionic      
**CPU architecture:** x86_64

## Command used to create docker container (run/create/compose/screenshot)

docker create \
  --name=unifi-controller \
  -e PUID=1000 \
  -e PGID=1000 \
  -e MEM_LIMIT=1024M `#optional` \
  -p 192.168.1.46:3478:3478/udp \
  -p 10001:10001/udp \
  -p 192.168.1.46:8080:8080 \
  -p 192.168.1.46:8081:8081 \
  -p 192.168.1.46:8443:8443 \
  -p 192.168.1.46:8843:8843 \
  -p 192.168.1.46:8880:8880 \
  -p 192.168.1.46:6789:6789 \
  -v path to data:/config \ `#original location (soft link). OR...`
  -v path to data:/usr/lib/unifi \ `#for most everything. If you use this then skip the other two`
  -v path to data:/usr/lib/unifi/data/sites \ `#for usg config file`
  -v path to data:/usr/lib/unifi/data/backup/autobackup \ `#for backups`
  --restart unless-stopped \
  linuxserver/unifi-controller

**Comment by aptalca** [comment]
We already symlink all data locations to `/config`: https://github.com/linuxserver/docker-unifi-controller/blob/master/root/etc/cont-init.d/20-config#L8-L18

Here are the symlinks on my machine:
```
# docker exec unifi-controller ls -al /usr/lib/unifi
total 12
drwxr-xr-x 1 abc  users   52 Jan 26 21:23 .
drwxr-xr-x 1 root root   346 Jan 25 10:35 ..
drwxr-xr-x 1 abc  users   56 Jan 25 10:36 bin
lrwxrwxrwx 1 abc  users   12 Jan 26 21:23 data -> /config/data
drwxr-xr-x 1 abc  users   16 Jan 25 10:35 dl
drwxr-xr-x 1 abc  users 5968 Jan 25 10:36 lib
lrwxrwxrwx 1 abc  users   12 Jan 26 21:23 logs -> /config/logs
lrwxrwxrwx 1 abc  users   11 Jan 26 21:23 run -> /config/run
drwxr-xr-x 1 abc  users    8 Jan 25 10:35 webapps
```

It seems you are breaking our symlink logic by mapping unnecessary mount points. You are also likely breaking all updates by mounting the app folder at `/usr/lib/unifi`.

Remove the container and delete the config folder. Start fresh and only mount `/config`, nothing else

**Comment by icarus747** [comment]
Hello, 
I see.  When I looked up the location of where to put the persistent file for openVPN I was going by the cloud key location and didn't realize the symlink was the same.  Then went I went looking for the issue of why my backups weren't showing up I related to the timestamps (in my pc, no the post) was the same time I upgraded to the new version.  At that point the symlink only showed the nested data folder due to the incorrect mounts.

Than you for your explanation.

**Comment by aptalca** [comment]
All of our images use the `/config` folder for user data. We list all pertinent mount points in our docker create and compose samples in the readmes. Of course you can add more mount points for additional data like media folders for plex/emby, but don't mount any existing folders inside the image. Mount any data folders to nonexistent paths like `/data/movies`, etc.
