### ISSUE TITLE
Devices not detected in bridge mode

### ISSUE THREAD

**Issue by belliash** [linuxserver/docker-unifi-controller#36]
Hey,

I am trying to setup UniFi controller in Docker container, but it does not detect any devices. I use the exact command specified in readme and controller itself is working. The `docker ps` command lists all ports. What is more I specify the same IP in Controller configuration and check 'Override inform host with controller hostname/IP'. Nevertheless, devices are still not seen.

On the other hand, everything works fine, when I use --net=host instead. But unfortunately, it listens on 0.0.0.0 then instead of single interface, what is unacceptable for me.

**Comment by belliash** [comment]
I noticed that it works with bridge networking as well. It stops working when I specify IP in /etc/docker/daemon.json ...

**Comment by j0nnymoe** [comment]
@belliash as mentioned in the readme, you need to use ssh in and set the inform URL if using bridge mode.

**Comment by belliash** [comment]
Thats what I did, but no luck.

**Comment by drizuid** [comment]
Why are you specifying an ip in /etc/docker/daemon.json? can you replicate the issue when you do not modify the behavior of docker globally? 
I run this in bridge mode and service, from my home, a unifi network 900 miles away and another 410 miles away with 0 issues.
