### ISSUE TITLE
Unifi controller keeps crashing / mongodb connection problems

### ISSUE THREAD

**Issue by mkliche** [linuxserver/docker-unifi-controller#37]
Hey,

I installed your container on my NAS system. The container starts fine, but several times per day the Web admin UI doesn't respond anymore. Container is still running. The only thing I can do is restart the container, then it works again.

I attached my server log. It shows many mongodb connection issues. Any ideas how to fix that problem? Thanks in advance!
[unifi.log](https://github.com/linuxserver/docker-unifi-controller/files/4480132/unifi.log)

**Comment by enoch85** [comment]
@mkliche Please try the latest release. It's updated to MongoDB 3.6 and Ubuntu 18.04. 

Please close this issue if it's not relevant anymore, or if it's working after you've tested the new release.
