### ISSUE TITLE
Adoption Fails without Ticking Extra Checkbox

### ISSUE THREAD

**Issue by kevinkreiser** [linuxserver/docker-unifi-controller#38]
The README very helpfully mentions that you have to change the Controller Hostname/IP. Unfortunately it doesn't mention that you need to tick the checkbox labelled: 

    Override inform host with controller hostname/IP

I think it would be good to amend the README to include that information. Perhaps a previous version of the controller didn't have that checkbox?

Anyway thanks for the nice project (removed a massive dependency headache of installing the controller on my host distro).

**Comment by ryanerwin** [comment]
@kevinkreiser  thanks so much for pointing this out... Spent a few hours with adoption trying to get devices to adopt before I saw your post...

**Comment by simbesh** [comment]
This gave me headaches for the longest time!

**Comment by kevinkreiser** [comment]
Well that's a shame

**Comment by j0nnymoe** [comment]
Is it not this? 
![image](https://user-images.githubusercontent.com/10374553/128594403-9f153b1c-511e-4dda-8189-c275bfd2d6a6.png)

**Comment by kevinkreiser** [comment]
Cool looks like they just forgot to close this
