### ISSUE TITLE
30-keygen failed on fresh Raspberry Pi 4 Ubuntu 20.04 64bit

### ISSUE THREAD

**Issue by yeawellwhatever** [linuxserver/docker-unifi-controller#40]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

The controller starts without issues
## Current Behavior

Step 30-keygen fails to run
## Steps to Reproduce

1. Grab latest Ubuntu 20.04 64bit from canonical, install docker.io and docker-compose
2. Create docker-compose.yml and docker-compose up

## Environment
**OS:** Ubuntu 20.04 64bit     
**CPU architecture:** arm64      
**How docker service was installed:**      

apt-get install docker.io docker-compose
everything else is default.
Raspberry Pi with 4G RAM was used.
## Command used to create docker container (run/create/compose/screenshot)

mkdir unifi
vim compose.yml
docker-compose up 

Not sure if related, but I cant get jacobalberty/unifi-docker to run either. both mongo 3.4 and 3.6 fails to start on arm64 with the error `Assertion failure getrlimit`
## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
_         ()
| |  ___   _    __
| | / __| | |  /  \ 
| | \__ \ | | | () |
|_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
library initialization failed - unable to allocate file descriptor table - out of memory/var/run/s6/etc/cont-init.d/30-keygen: line 7:   223 Aborted                 (core dumped) keytool -genkey -keyalg RSA -alias unifi -keystore /config/data/keystore -storepass aircontrolenterprise -keypass aircontrolenterprise -validity 1825 -keysize 4096 -dname "cn=unifi"
chown: cannot access '/config/data/keystore': No such file or directory
[cont-init.d] 30-keygen: exited 1.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
library initialization failed - unable to allocate file descriptor table - out of memorylibrary initialization failed - unable to allocate file descriptor table - out of memorylibrary initialization failed

**Comment by tobbenb** [comment]
I just tested it on a PI 4 Ubuntu 20.04 and see the same. I think this have to do with installing docker from the ubuntu repo and not from docker.com. But I know docker.com haven't released it yet for 20.04.
I have no idea what is causing this, but a quick google search hints to ulimit.

**Comment by yeawellwhatever** [comment]
You were right, it was docker from the ubuntu repo. I used Docker static binaries from docker themselves and it worked. 

Now Im not sure if it's because how Ubuntu/Debian compiled/linked the docker binaries, or it's something on their default config.

For those looking for steps to install docker static binaries, check out the link below. 
https://docs.docker.com/engine/install/binaries/

**Comment by tobbenb** [comment]
Typical. We always reccomend dockers own binaries.
Docker have not released their binaries for 20.04 in their deb repo and I didn't think of the static binaries at all when I  tested

**Comment by yeawellwhatever** [comment]
Okay, more weird stuff. I tried installing from Docker Inc repo using `deb [arch=arm64] https://download.docker.com/linux/ubuntu eoan stable` , and I got the same error. Now I truly have no clue if the issues is with Ubuntu/Debian package docker.io or it's somewhere else. 

Guess we'll have to make do with the static binaries and wait for the official docker-ce 20.04 release.

**Comment by djchen** [comment]
I just ran into the same issue on a Raspberry Pi 4 running Ubuntu 20.04 Focal (64-bit) and using the Docker CE from Docker Inc repo.

I tried to manually build the AArch64 Dockerfile on the Pi and got this error:
```
 ---> Running in 188e9644f6ce
**** add mongo repository ****
gpg: fatal: can't disable core dumps: Operation not permitted
secmem usage: 0/0 bytes in 0/0 blocks of pool 0/0
```

When I modified the Dockerfile.aarch64 and replace xenial with focal, I progressed a bit further and then ran into:
```
**** install packages ****
Ign:1 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 InRelease
Get:2 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 Release [3,457 B]
Get:3 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 Release.gpg [801 B]
Get:4 http://ports.ubuntu.com/ubuntu-ports focal InRelease [265 kB]
Get:5 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4/multiverse arm64 Packages [16.4 kB]
Get:6 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4/multiverse amd64 Packages [16.4 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [89.1 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease [89.2 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease [97.9 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports focal/universe arm64 Packages [11.1 MB]
Get:11 http://ports.ubuntu.com/ubuntu-ports focal/restricted arm64 Packages [1,317 B]
Get:12 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 Packages [1,234 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports focal/multiverse arm64 Packages [139 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 Packages [1,959 B]
Fetched 13.1 MB in 6s (2,190 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mongodb-org-server : Depends: libssl1.0.0 (>= 1.0.2~beta3) but it is not installable
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c echo "**** add mongo repository ****" &&  apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6 &&  echo "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" >> /etc/apt/sources.list.d/mongo.list &&  echo "**** install packages ****" &&  apt-get update &&  apt-get install -y 	binutils 	jsvc 	mongodb-org-server 	openjdk-8-jre-headless 	wget &&  echo "**** install unifi ****" &&  if [ -z ${UNIFI_VERSION+x} ]; then 	UNIFI_VERSION=$(curl -sX GET http://dl-origin.ubnt.com/unifi/debian/dists/${UNIFI_BRANCH}/ubiquiti/binary-amd64/Packages 	|grep -A 7 -m 1 'Package: unifi' 	| awk -F ': ' '/Version/{print $2;exit}' 	| awk -F '-' '{print $1}');  fi &&  curl -o  /tmp/unifi.deb -L 	"https://dl.ui.com/unifi/${UNIFI_VERSION}/unifi_sysvinit_all.deb" &&  dpkg -i /tmp/unifi.deb &&  echo "**** cleanup ****" &&  apt-get clean &&  rm -rf 	/tmp/* 	/var/lib/apt/lists/* 	/var/tmp/*' returned a non-zero code: 100
```

**Comment by twoequaldots** [comment]
I ran into a similar issue when the container was running `30-keygen` script.  My error was primarily this:
```
library initialization failed - unable to get max # of allocated fds
```

I `exec` into the container and ran the below:
```
root@0c95240a0c0d:/usr/lib/unifi# ulimit -Sn
bash: ulimit: open files: cannot get limit: Operation not permitted
root@0c95240a0c0d:/usr/lib/unifi# ulimit -Hn
bash: ulimit: open files: cannot get limit: Operation not permitted
```

I then tried to create a docker container using something like this:
```
sudo docker create --name=unifi-controller --ulimit nofile=262144:262144 -e PUID=1000 -e PGID=1000 -e MEM_LIMIT=1536M -p 3478:3478/udp -p 10001:10001/udp -p 8080:8080 -p 8081:8081 -p 8443:8443 -p 8843:8843 -p 8880:8880 -p 6789:6789 -v /opt/docker/unifi-data:/config --restart unless-stopped linuxserver/unifi-controller:latest
```

This did not work, I got the same error.  I then did some googling and found suggestions to try running the container in `--privileged` mode and that did the trick for me!  I'm not a fan of it and don't quite understand why (I spent some time digging through the docker.io.deb package from Ubuntu repo vs docker-ce from Docker repo and couldn't find any smoking gun yet).

This is the full command that worked for me but still isn't ideal:
```
sudo docker create --name=unifi-controller --privileged -e PUID=1000 -e PGID=1000 -e MEM_LIMIT=1536M -p 3478:3478/udp -p 10001:10001/udp -p 8080:8080 -p 8081:8081 -p 8443:8443 -p 8843:8843 -p 8880:8880 -p 6789:6789 -v /opt/docker/unifi-data:/config --restart unless-stopped linuxserver/unifi-controller:latest
```

**Comment by xdbob** [comment]
Just dropping by to say its a bug in libseccomp witch blacklisted `{get,set}rlimit` on aarch64 that is now fixed upstream: https://github.com/seccomp/libseccomp/commit/7780b0853eff8521bbf79611656c68fadc1dab3d

In the meantime I have a "better" workaround `docker create --name=unifi-controller -e PUID=1000 -e PGID=1000 -p 3478:3478/udp -p 10001:10001/udp -p 8080:8080 -p 8081:8081 -p 8443:8443 -p 8843:8843 -p 8880:8880 -p 6789:6789 --restart unless-stopped --security-opt=seccomp=unconfined linuxserver/unifi-controller:latest`
I didn't look too had but it seams that syscalls cannot be whitelisted by their number.

**Comment by enoch85** [comment]
This issue should be solved by now right? This now works on Ubuntu 20.04 RPi 4 again:

`curl -fsSL get.docker.com | sh`

**Comment by yeawellwhatever** [comment]
Probably, I dont have the actual environment to test anymore. I've  moved to stock Debian, and seems to be running from a quick run.

**Comment by twoequaldots** [comment]
This was closed ~2 months ago but I wanted to say that I switched from Ubuntu's docker package to Docker's ubuntu repo and all works as planned (when Ubuntu first came out for rpi4, it took a couple of months for Docker folks to create an ARM repo for 20.04).
