### ISSUE TITLE
mongodump/mongorestore (mongo-tools) missing

### ISSUE THREAD

**Issue by jens-maus** [linuxserver/docker-unifi-controller#41]
## Expected Behavior
For developing purposes I would like to use your unifi-controller docker image but unfortunately it is missing the `mongodump` and `mongorestore` tools which are usually part of the `mongo-tools` package.

## Current Behavior
`mongodump` and `mongorestore` are missing binaries to be able to dump+restore the mongo database accordingly.

## Steps to Reproduce
1. try to start `mongodump` or `mongorestore` within the docker environment.

**Comment by aptalca** [comment]
You can easily add them by exec'ing into the container by `docker exec -it unifi-controller bash` and doing `apt update && apt install mongo-tools` (if that's the package name).
They will disappear after the container is recreated (updated)
To make them persistent, you can see here: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by jens-maus** [comment]
@aptalca Thanks for the hint, didn't think about that. The actual package that needs to be installed is `mongodb-org-tools` and then `mongodump` and `mongorestore` are available.
