### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by enoch85** [linuxserver/docker-unifi-controller#50]
Thanks for a great docker image!

I looked into the dependencies and found that it runs on MongoDB 3.4 and Java 8. These could/should be replaced/updated with MongoDB 3.6 and Java 11 instead IMHO.

Regarding MongoDB 3.6, [that just got supported in Unifi](https://community.ui.com/releases/UniFi-Network-Controller-5-13-29/d7647910-77a2-4e61-bbfe-389206f2d6ad), and regarding Java 11, you need to change the `unifi.service` to [this](https://community.ui.com/questions/Running-Unifi-Controller-on-Java-9-10-and-11/f1ac1330-40b8-4af6-83b6-8d55e48e4a32#answer/8d76f4fa-b9fd-423b-ac51-cf50a22776b9).

It would also be nice to add a text editor, like nano for example.

I fail to get internet connectivity from within the Docker, but maybe that's another issue?

**Comment by j0nnymoe** [comment]
There are no arm binaries for mongodb 3.6 so we don't plan to update the dependencies at this time.

If you want to add a text editor, use this https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

And can't help with the other issue but it sounds like a networking issue on your end.

**Comment by enoch85** [comment]
Aah great, thanks!

Yeah, you're right. It was on my end with the netowokring. Running Pi-Hole and had set to only listen to eth0. When changing to all network interfaces it started to work.

I'm surprised with MongoDB 3.6. Installing the controller nativity on my Pi 4 allows (and works) with both 3.6 and Java 11... It's Ubuntu though, which OS is this docker based on?

**Comment by enoch85** [comment]
And yeah, I was right this time:

```
root@raspberrypi:~# docker exec -it unifi-controller bash
root@748ba193c400:/usr/lib/unifi# sudo apt install -y mongodb-org^C
root@748ba193c400:/usr/lib/unifi# dpkg -l | grep mongo
ii  mongodb-org                          3.6.18                                arm64        MongoDB open source document-oriented database system (metapackage)
ii  mongodb-org-mongos                   3.6.18                                arm64        MongoDB sharded cluster query router
ii  mongodb-org-server                   3.6.18                                arm64        MongoDB database server
ii  mongodb-org-shell                    3.6.18                                arm64        MongoDB shell client
ii  mongodb-org-tools                    3.6.18                                arm64        MongoDB tools
rc  mongodb-server                       1:2.6.10-0ubuntu1                     arm64        object/document-oriented database (server package)
root@748ba193c400:/usr/lib/unifi# 
```

It's possible when using their own repos. Just an example: https://websiteforstudents.com/install-mongodb-on-ubuntu-18-04-lts-beta-server/

Requires `apt-transport-https` though.

**Comment by enoch85** [comment]
Actually, there's already a PR for it: https://github.com/linuxserver/docker-unifi-controller/pull/49

**Comment by dam09fr** [comment]
@enoch85 arm64 is available from mongodb repo, but from what I can see arm32 is not ...

**Comment by enoch85** [comment]
Oh ok. :/

Would it be possible to check if it's 32 or 64 bit and install accordingly (with like if 64-bit; then...)?

**Comment by j0nnymoe** [comment]
We'll likely keep this on mongodb3.4 until we're forced to move up to 3.6. Hopefully there will be an arm binary for 3.6 by then but if not, I suspect we will just drop support for arm32 and just have arm64 and x86.

**Comment by enoch85** [comment]
Ok, if not MongoDB 3.6 I would have to say thanks but no thanks.

Great image ither than that.

Thanks!
