### ISSUE TITLE
Default Unifi Controller Login Information

### ISSUE THREAD

**Issue by kubilayelmas** [linuxserver/docker-unifi-controller#53]
Can't figure out what is the username and password to use on the default configuration of the unifi controller with the dashboard configuration wizard. Am I missing something?

**Comment by tobbenb** [comment]
Setting up the username/password is a step in the wizard.

**Comment by kubilayelmas** [comment]
Hi,
Thanks for your reply.

Exactly, I'm at the step 2 of the wizard "Sign in with your Ubiquiti Account" and can't pass trough this...

**Comment by tobbenb** [comment]
There should be an option to skip that and create a local account.

**Comment by tristanMatthias** [comment]
I am also experiencing this. Steps:
1. Fresh docker compose
2. Open http://0.0.0.0:8080/
3. **Wizard Step 1:** Enter controller name
4. **Wizard Step 2:** Click "Switch to advanced setup"
5. Fill out details
6. **Wizard Step 3 of 7 (advanced):** Use credentials just entered in step 2
7. Returns "Invalid username or password, please try again."

Is there a way to configure this in the docker container?

**Comment by aptalca** [comment]
I just ran `docker run -d --rm --name test -p 8443:8443 ghcr.io/linuxserver/unifi-controller` which put up a fresh test container, accessed the gui, hit advanced and set up a new local user with no issues.

Did you forget to uncheck `Use your Ubiquiti account for local access`? That's where it asks you to create a new user

**Comment by tristanMatthias** [comment]
Yeah, so just ran that exact command (had to open the 8080 port too)
Filled in these credentials:
Username: somos
Password: somos
<img width="421" alt="image" src="https://user-images.githubusercontent.com/2550138/104653756-181d1700-5689-11eb-8ba6-d879b29a8f6c.png">

Then clicked next:
<img width="435" alt="image" src="https://user-images.githubusercontent.com/2550138/104653835-33882200-5689-11eb-8b56-ed34da65b8e9.png">
Filled in with somos and somos as password. 
Same error

**Comment by j0nnymoe** [comment]
Got a password manager or anything running in your browser? Try using an private window to set it up.

**Comment by tristanMatthias** [comment]
Yeah, tried that too. Exact same issue

**Comment by tristanMatthias** [comment]
Running OSX Catalina FWIW. Also tried other browsers and private windows

**Comment by aptalca** [comment]
You're confusing ubiquiti account with a local one
The one you create in step 2 is a local account, not related to a ubiquiti acct
In step 3, it's asking you for a ubiquiti account, which is an online one you create on their website and is optional

**Comment by tristanMatthias** [comment]
How is it optional? I can't get past this stage. I'm very happy to create one btw. Just thought I could do all of this isolated to our internal envionment.

**Comment by aptalca** [comment]
Uncheck `Enable remote access`, which requires a ubiquiti acct

**Comment by davidbdeath** [comment]
I made a local account but is there a fix for logging in with your unifi account?

**Comment by aptalca** [comment]
fix for what exactly?

**Comment by davidbdeath** [comment]
for logging in with a unifi account

**Comment by aptalca** [comment]
you say fix, but what exactly is broken about it?

**Comment by fermulator** [comment]
same problem

There was an error enabling Remote Access. UniFi's remote access service cannot be reached. Please check your network connection and try again.
