### ISSUE TITLE
Container does not start

### ISSUE THREAD

**Issue by florie1706** [linuxserver/docker-unifi-controller#56]
Unfortunately the container does not start. I copied your docker-compose to a file and tried to start it.
It keeps hanging at **[cont-init.d] 20-config: executing...**

_root@nas: docker-compose up --force-recreate_

Recreating unifi-controller ... done
Attaching to unifi-controller
unifi-controller    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
unifi-controller    | [s6-init] ensuring user provided files have correct perms...exited 0.
unifi-controller    | [fix-attrs.d] applying ownership & permissions fixes...
unifi-controller    | [fix-attrs.d] done.
unifi-controller    | [cont-init.d] executing container initialization scripts...
unifi-controller    | [cont-init.d] 01-envfile: executing...
unifi-controller    | [cont-init.d] 01-envfile: exited 0.
unifi-controller    | [cont-init.d] 10-adduser: executing...
unifi-controller    |
unifi-controller    | -------------------------------------
unifi-controller    |           _         ()
unifi-controller    |          | |  ___   _    __
unifi-controller    |          | | / __| | |  /  \
unifi-controller    |          | | \__ \ | | | () |
unifi-controller    |          |_| |___/ |_|  \__/
unifi-controller    |
unifi-controller    |
unifi-controller    | Brought to you by linuxserver.io
unifi-controller    | -------------------------------------
unifi-controller    |
unifi-controller    | To support LSIO projects visit:
unifi-controller    | https://www.linuxserver.io/donate/
unifi-controller    | -------------------------------------
unifi-controller    | GID/UID
unifi-controller    | -------------------------------------
unifi-controller    |
unifi-controller    | User uid:    1000
unifi-controller    | User gid:    1000
unifi-controller    | -------------------------------------
unifi-controller    |
unifi-controller    | [cont-init.d] 10-adduser: exited 0.
unifi-controller    | [cont-init.d] 20-config: executing...

**Comment by j0nnymoe** [comment]
Please post your compose so we can review it. Also please let us know your host os etc (as per requested in the issue template.

**Comment by florie1706** [comment]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.



------------------------------

## Expected Behavior
Container should start ;)

## Current Behavior
It does not start and keeps hanging @ unifi-controller | [cont-init.d] 20-config: executing...

## Steps to Reproduce
Use docker-compose.yml from your github repository:

`version: "2.1"
services:
  unifi-controller:
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M #optional
    volumes:
      - <path to data>:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514 #optional
    restart: unless-stopped`

## Environment
**OS:**      Ubuntu Server 20.04.1 LTS
**CPU architecture:** x86_64      
**How docker service was installed:** Thru Ubuntu's apt command

## Command used to create docker container (run/create/compose/screenshot)
docker-compose up --force-recreate

**Comment by Doctor-Mo** [comment]
I also encountered this issue minutes ago.
I even tryed downgrading to Version `5.6.42-ls87` but still i dont get any further than `executing...`

Im using the stock Docker-compose from the docs

**Comment by j0nnymoe** [comment]
@florie1706 unifi hanging at that point means it's generating ssl files which can take a different amount of time depending on the host etc. Leave it to run and it will complete and boot up.

**Comment by j0nnymoe** [comment]
@Doctor-Mo as above.

I've recently deployed the container to an older machine and it takes a while yet on another box I have, it's almost instant.

**Comment by florie1706** [comment]
Oh yeah, you are right. The strang thing about this for me was, taht my laptop and another pc did it like in seconds while the server needed 11 minutes. That said the server is the most powerful machine in my house. But thanks for your comment that took me to try it again and wait until it finished ;)

**Comment by j0nnymoe** [comment]
@florie1706 I believe it's an issue with the default storage driver and using overlay2 - some people are hit with the bug yet others aren't.
