### ISSUE TITLE
Do you plan to add 6.x branch?

### ISSUE THREAD

**Issue by sanyer** [linuxserver/docker-unifi-controller#57]
There is new version of controller being developed by Ubiquity - https://community.ui.com/releases/UniFi-Network-Controller-6-0-18/5869a608-5e12-4df8-ab1b-674a906d996d

And since it is a simple change of UNIFI_VERSION, would you consider adding a branch for it?
For now, I've built the image locally with `--build-arg UNIFI_VERSION=6.0.18-2f53410e48` and pushed to my own dockerhub repo, but it would be really good to be able to install it from `linuxserver/unifi-controller` :-)

**Comment by aptalca** [comment]
When it's published in their apt repo, our Jenkins should pick it up and build it shortly after

**Comment by sanyer** [comment]
yeah, it will take a while

**Comment by ses4j** [comment]
@sanyer In the meantime, can you publish the url of the one you pushed?

**Comment by ses4j** [comment]
@sanyer Nevermind, I managed to replicate.  For anyone else needing controller v6.x before it gets pushed to the official repository, here is a repository for v6.0.20:

`ses4j/docker-unifi-controller-6:latest`

Built via:

```
git clone git@github.com:linuxserver/docker-unifi-controller.git
cd docker-unifi-controller
docker build --no-cache --pull --build-arg UNIFI_VERSION=6.0.20-816b9dfcdd -t ses4j/docker-unifi-controller-6:latest -t ses4j/docker-unifi-controller-6:latest . 
docker push ses4j/docker-unifi-controller-6:latest
```

**Comment by sanyer** [comment]
@ses4j I've just bought a UDM, so don't the need this image for now 👼 
Thanks for sharing the workaround. btw, you have two identical tags in your command.
