### ISSUE TITLE
Multiple Controllers on a Single Host + SWAG

### ISSUE THREAD

**Issue by notlimahrelyt** [linuxserver/docker-unifi-controller#58]
Hello All,

Not so much an 'issue' here, more as a how-to.

Does anyone have experience running this with multiple controllers on a single host? The scenario is i'm looking to host my controller as well as additional clients controllers. This is also utilizing linuxserver/swag for reverse proxying each clients URL.

Example: 

unifi.clientA.com resolves to a controller
unifi.clientB.com resolves to a separate controller
unifi.clientC.com resolves to a separate controller

etc.

Thank you!

**Comment by Roxedus** [comment]
It should be as easy as setting the `server_name` in the proxy file to the actual domain for the specified container, as the default way is to take any domain. So something like this
```nginx
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name unifi.clientA.com;


    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app unifi-controllerA;
        set $upstream_port 8443;
        set $upstream_proto https;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        proxy_buffering off;
    }
}
```

**Comment by notlimahrelyt** [comment]
@Roxedus Thank you for the reply - That makes sense, i think the NGINX block is easy enough, the issue i'm running into is how to configure the docker-compose file without overlapping ports. Is there a clean way to do this other than staggering the port numbers?

Example:  3478:3478, 3479:3478, 3480:3478

Thanks!

**Comment by Roxedus** [comment]
Not really. But i do think the site feature in the controller would fit better in your setup

**Comment by notlimahrelyt** [comment]
@Roxedus - Fair enough, was hoping for a cleaner setup than just staggering the port numbers. I think Sites could be useful as well, but my clients want their own controller under their domain. I'm just trying to figure out how to best host it for them.

**Comment by PrplHaz4** [comment]
> 
> 
> @Roxedus - Fair enough, was hoping for a cleaner setup than just staggering the port numbers. I think Sites could be useful as well, but my clients want their own controller under their domain. I'm just trying to figure out how to best host it for them.

You could give each container its own IP with the macvlan driver - this would allow you to use the same ports for each.
