### ISSUE TITLE
Unifi controller does not start when updating to version 6.0.36

### ISSUE THREAD

**Issue by weha** [linuxserver/docker-unifi-controller#64]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Everything started

## Current Behavior
The container starts and hangs on the following command: chown -R abc:abc /config /usr/lib/unifi

## Steps to Reproduce
This happened when I updated to 6.0.36
I tried going back to 6.0.28 but that remained the same, which I find weird but ok.
Tried 6.0.36 again and went into the console and saw the chown command.
I tried to chown the webapps folder (only one not correct) in /usr/lib/unifi and was met with the same hang.
Killed chown -> unifi started

## Environment
**OS:** unraid 6.9.0beta35
**CPU architecture:** x86_64
**How docker service was installed:** 
The container was installed with latest tag, now 6.0.36-ls87

## Command used to create docker container (run/create/compose/screenshot)
Community apps

## Docker logs
It would stop at 20-config

    today at 7:47 AM  [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
    today at 7:47 AM  [s6-init] ensuring user provided files have correct perms...exited 0.
    today at 7:47 AM  [fix-attrs.d] applying ownership & permissions fixes...
    today at 7:47 AM  [fix-attrs.d] done.
    today at 7:47 AM  [cont-init.d] executing container initialization scripts...
    today at 7:47 AM  [cont-init.d] 01-envfile: executing... 
    today at 7:47 AM  [cont-init.d] 01-envfile: exited 0.
    today at 7:47 AM  [cont-init.d] 10-adduser: executing... 
    today at 7:47 AM  
    today at 7:47 AM  -------------------------------------
    today at 7:47 AM            _         ()
    today at 7:47 AM           | |  ___   _    __
    today at 7:47 AM           | | / __| | |  /  \ 
    today at 7:47 AM           | | \__ \ | | | () |
    today at 7:47 AM           |_| |___/ |_|  \__/
    today at 7:47 AM  
    today at 7:47 AM  
    today at 7:47 AM  Brought to you by linuxserver.io
    today at 7:47 AM  -------------------------------------
    today at 7:47 AM  
    today at 7:47 AM  To support LSIO projects visit:
    today at 7:47 AM  https://www.linuxserver.io/donate/
    today at 7:47 AM  -------------------------------------
    today at 7:47 AM  GID/UID
    today at 7:47 AM  -------------------------------------
    today at 7:47 AM  
    today at 7:47 AM  User uid:    99
    today at 7:47 AM  User gid:    100
    today at 7:47 AM  -------------------------------------
    today at 7:47 AM  
    today at 7:47 AM  [cont-init.d] 10-adduser: exited 0.
    today at 7:47 AM  [cont-init.d] 20-config: executing... 
    today at 8:02 AM  /var/run/s6/etc/cont-init.d/20-config: line 23:   242 Terminated              chown -R abc:abc /config /usr/lib/unifi
    today at 8:02 AM  [cont-init.d] 20-config: exited 143.
    today at 8:02 AM  [cont-init.d] 30-keygen: executing... 
    today at 8:02 AM  [cont-init.d] 30-keygen: exited 0.
    today at 8:02 AM  [cont-init.d] 99-custom-scripts: executing... 
    today at 8:02 AM  [custom-init] no custom files found exiting...
    today at 8:02 AM  [cont-init.d] 99-custom-scripts: exited 0.
    today at 8:02 AM  [cont-init.d] done.
    today at 8:02 AM  [services.d] starting services
    today at 8:02 AM  [services.d] done.

**Comment by j0nnymoe** [comment]
I will test tonight but it seems that the build itself does work as it passed our tests: https://ci-tests.linuxserver.io/linuxserver/unifi-controller/latest/index.html

**Comment by j0nnymoe** [comment]
Upgraded to 6.0.36 and working as expected:
```
-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.```
![image](https://user-images.githubusercontent.com/10374553/100011791-29088500-2dca-11eb-94ac-8c02e14dfb04.png)

**Comment by weha** [comment]
What I think happened is that there are probably a lot of files in that webapp folder?
Docker is running on normal disks so it probably took ages to just get the changes written to disk...
Thanks for checking!

**Comment by w-t-p** [comment]
I am having this exact issue.
Host: Windows 10 20H2
Docker Desktop 3.0.4 running in WSL2 mode.
Killing the chown allows it to boot correctly.
Other identical systems work fine with the same docker-compose.yml file.
Convinced its something to do with my docker-desktop-data file having odd permissions inside of it.
I've tried playing with different permanent containers, temporary containers, resetting Docker Desktop entirely (and restoring my ext4.vhdx back due to other Docker volumes I can't remove).

How can I modify or verify permissions on the actual docker-desktop-data ext4.vhdx?

Again - everyhting the same - I go to another machine and run the exact same docker-compose file and the issue does nor occur so I strongly suspect its related to my ext4.vhdx which holds Docker volumes.

**Comment by w-t-p** [comment]
Wait. Wait. Wait.
In the process of writing the above blurb it successfully completed boot.
Successive reboots work without issue - the start-up script must know all is well and not run the chown command.
Not sure why performance is so different on the other machines but that was a good 10+ minutes.
Might be a warning you could "echo" out on boot for those who do not wait long enough (like me).
Thanks
