### ISSUE TITLE
Repeating Crashes Every ~25 Minutes

### ISSUE THREAD

**Issue by backlands** [linuxserver/docker-unifi-controller#73]
## Expected Behavior
The container should remain running for long periods of time.

## Current Behavior
The container appears to be crashing due to URL rewriting, I am not sure if this is a configuration issue on my end, an issue directly with the Unifi Controller, or an issue within the docker itself.

## Steps to Reproduce
I am uncertain about how to reproduce this as I have been unable to track down what might be causing it. Let me know if you want me to jump into a chat or call on Discord to troubleshoot quickly. I am going to continue trying to find the source of the problem on my end and will update with what I find.

As of now the most apparent line in my logs is this `org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: destroy called` which I have not been able to find to much info about through my searches so far (besides one article suggesting rebuilding the entire controller database...).

P.S. If this isn't the place for this bug report, feel free to let me know and close this issue, I am just getting to that point with the issue where I am hitting a wall and wanted to try this!

## Environment
**OS:** unRAID
**CPU architecture:** x86_64
**How docker service was installed:** Using unRAID docker management through Apps interface

## Command used to create docker container
![2021-02-25-120830_1241x862_scrot](https://user-images.githubusercontent.com/12586299/109204140-3be07c00-7762-11eb-9675-5c306ff9dc41.png)

## Docker logs
```
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[01;33m:0 Permanent error code on channel bind request: 400 - Empty port number in channel bind request[22;37m
[01;33m:0 All TURN channel bindings failed[22;37m
[01;33m:0 STUN id: 6; fd: 233 *************:36699 -> *************:49469 (br0) DTLS id: 0 () (PEER) timed out[22;37m
[01;33m:0 STUN id: 7; fd: 233 *************:36699 -> *************:43984 (br0) DTLS id: 0 () (PEER) timed out[22;37m
[01;33m:0 STUN id: 8; fd: 200 *************:50455 -> *************:49469 (docker0) DTLS id: 0 () (PEER) timed out[22;37m
[01;33m:0 STUN id: 9; fd: 200 *************:50455 -> *************:43984 (docker0) DTLS id: 0 () (PEER) timed out[22;37m
[01;33m:0 All TURN channel bindings failed[22;37m
[01;31m:0 SSL_read permanently failed: (6) [22;37m
[01;31m:0 Unable to do SSL I/O[22;37m
[01;33m:0 webRtcId 2 terminated with code: (-2147090409) WebRTC connection interrupted from far side[22;37m
org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: destroy called
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes
```

**Comment by aptalca** [comment]
Don't use host networking

**Comment by backlands** [comment]
Curious, I had a drive failed recently and had to reconfigure some of my containers after that. Might have changed the setting at that point.

Let me give it a try in bridged mode and see if it resolves the issue. Good catch.
