### ISSUE TITLE
Have a tag per version branch, e.g 6.0, 6.1 (and 5.6 for the legacy version)

### ISSUE THREAD

**Issue by kosli** [linuxserver/docker-unifi-controller#76]
Currently there is no tag to stay on e.g. the 6.0 branch of the UniFi controller. I see that for previous versions there is a 5.7, 5.8 and 5.9 tag.
It would be great to have a 6.0, 6.1 and even 5.6 tag for the latest version of that branch, e.g. 
- 6.0 -> 6.0.45-ls99
- 6.1 -> 6.1.71-ls102
- 5.6 -> 5.6.42-ls96

I know I can use the version-6.0.45 tags to stay with a specific version, but if there would be a version-6.0.66 i would need to check to see that there is a newer version.

Thanks.

**Comment by aptalca** [comment]
Unifi used to have support multiple stable release tracks and that's why we had multiple tags. They no longer do that and only publish one stable. No point in us maintaining multiple tags.

**Comment by kosli** [comment]
Thanks @aptalca I got your point. 

Whereas as user this means that if I want to be sure that my unifi controller doesn't get updated to a version that suddenly doesn't support older devices (like in the upgrade from 5.6 to 6.0 series), I cannot use a tag like `latest`, but will need to manually "track" and adapt my docker-compose e.g.:
```
6.0.41-ls88
6.0.41-ls89
6.0.41-ls90
6.0.41-ls91
6.0.43-ls92
6.0.43-ls93
6.0.43-ls94
6.0.43-ls95
6.0.45-ls96
6.0.45-ls97
6.0.45-ls98
6.0.45-ls99
6.0.45-ls100
```
You would not need to "maintain" multiple tags, as you would only maintain the tag for the stable branch, e.g. 6.1 and when that branch isn't the stable anymore, it would just be stuck on the version as-is. That would mean for the past that 5.6 and 6.0 would now be left at 
- 6.0 -> 6.0.45-ls99
- 5.6 -> 5.6.42-ls96

So everyone that had used the 5.6 tag in the past, would be stuck on the last release of 5.6, and everyone who wanted to always have the latest unifi controller, would have anyways used the `latest` tag. 

As a user I wouldn't have the risk that my unifi controller gets updated to a new series (which seems to make some users quite unhappy with the new 6.1 series https://community.ui.com/questions/Latest-UniFi-Controller-6-1-71-interface-is-HORRIBLE/d19b23dc-96d9-4ce6-89eb-12169f19962e ;-))

**Comment by aptalca** [comment]
There is a tag `version-6.0.45` which tracks that version when there are package updates but won't update to the next unifi version.

**Comment by kosli** [comment]
@aptalca yes i know, that is the one that i am currently using.
but if I would now "upgrade" to `latest` i would be (currently) on 6.1.71. But sometime in the future I would automatically be upgraded to the next stable branch, e.g. 8.0 -> so there is no way to make sure to stay on the same branch. so either I need to check the current tags before doing a `docker-compose pull` to not risk to be suddenly on version 8.0, which may be incompatible with devices that I am currently using, or I need to manually follow the tags to be notified when there is a new version of the 6.1 branch.

**Comment by Roxedus** [comment]
To achieve that, we would have to maintain a separate tag.

**Comment by kosli** [comment]
@Roxedus I think i start understanding what the problem may be: the tags are being created automagically from the releases on the UniFi page and that way you would need to "manually" create & maintain additional tags?

**Comment by j0nnymoe** [comment]
Closing as we have no plans to add this due to the reasons above.
