### ISSUE TITLE
Disable https for UI

### ISSUE THREAD

**Issue by joconcepts** [linuxserver/docker-unifi-controller#78]
Is it possible to have HTTPS disabled for the UI?

I've found this:
https://community.ui.com/questions/UniFi-controller-on-HTTP-No-HTTPS-the-solution/cf93c093-c87f-484f-b833-363446983c04

```
# /usr/lib/unifi/data/system.properties:
unifi.https.redirect=false

# /etc/default/unifi:
UNIFI_CORE_ENABLED=true
```

Is that possible with this docker container? I would like to run traefik in front of the UI.

**Comment by aptalca** [comment]
Any decent reverse proxy solution is able to reverse proxy https endpoints.

But if you really want to make those changes anyway, see https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
