### ISSUE TITLE
"latest" did downgrade from version-6.2.23 to version-6.1.71

### ISSUE THREAD

**Issue by p-schneider** [linuxserver/docker-unifi-controller#81]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
I would expect to be able to use the `:latest` tag without having to deal with version downgrade errors.

## Current Behavior

After having used the image "latest" for some time now and updating it frequently today the controller stopped working because it rejected the downgrade from 6.2.23 to 6.1.71.
Error Message when launching latest(=6.1.71) after latest(=6.2.23) had been used:
`we do not support upgrading from 6.2.23`

Related Commit: 6eff0f3 

##  Workaround
I now temporarily changed my container start script to use `docker.io/linuxserver/unifi-controller:version-6.2.23` instead of `docker.io/linuxserver/unifi-controller:latest`.

## Environment
**OS:** Ubuntu Linux 18.04.5
**CPU architecture:** x86_64
**How docker service was installed:** official docker repo

## Command used to create docker container (run/create/compose/screenshot)

persistent data folder mounted to `/config`, ports etc. and `-e PUID=1000 -e PGID=1000  -e MEM_LIMIT=1024M`

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2021-05-13 08:15:30,926 main ERROR Error processing element InMemoryAppender ([Appenders: null]): CLASS_NOT_FOUND
2021-05-13 08:15:31,128 main ERROR Unable to locate appender "InMemoryAppender" for logger config "root"
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by j0nnymoe** [comment]
This is due to unifi pulling a broken update. Nothing we can do other than suggest restoring a backup.

**Comment by p-schneider** [comment]
For me the `docker.io/linuxserver/unifi-controller:version-6.2.23` image seems to be just fine - so I'll just keep using it until `:latest` starts pointing at 6.2.23 or newer, again.

**Comment by j0nnymoe** [comment]
That's good to hear. Our smoke tests we do all passed when the container was built but we've already had users mention that 6.2.23 broke their setup so I'm not surprised unifi pulled the update.

**Comment by p-schneider** [comment]
The `version-6.2.25` image was released 4 hours ago, so those who had issues with the downgrade from `6.2.23` should now be able to upgrade to `:latest` or  `:version-6.2.25`.

**Comment by hitchan** [comment]
To my fellow unRAID users, when you switch back to ":latest" and it still doesn't work.
Go into the advanced docker view and remove the orphaned 6.2.23 image, then perform a force update on the unifi-controller image (make sure you have it set to ":latest" before you perform to forced update).
