### ISSUE TITLE
/usr/lib/unifi missing out-of-the-box

### ISSUE THREAD

**Issue by marksherman** [linuxserver/docker-unifi-controller#83]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Server start up when container is run using docker-compose. 

## Current Behavior
Server hangs during startup.

## Steps to Reproduce

1. Copy example docker-compose.yml from this repo into a file
2. Edit docker-compose.yml to add the local config overlay
3. run `docker-compose up`
4. Observe that it is hanging on the following log entry:
```
unifi-controller    | WARN Unable to load properties from '/usr/lib/unifi/data/system.properties' - /usr/lib/unifi/data/system.properties (No such file or directory)
```

To mitigate, I added `/usr/lib/unifi` as another overlay under volumes in docker-compose.yml. This allows the server to start, but it fails during setup as it still is missing things that should be in that folder. With that mitigation, the error is this:
```
unifi-controller    | Error: Unable to access jarfile /usr/lib/unifi/lib/ace.jar
```

Something appears to me missing from the image construction to fully install the server, or maybe there is some docker trickery that's malfunctioning. 

## Environment
**OS:** Ubuntu 20.04.2 LTS arm64 / MacOS Big Sur 11.3.1 x86_64
**CPU architecture:** arm64 / x86_64/
**How docker service was installed:** via docker ppa / official docker install download

## Command used to create docker container (run/create/compose/screenshot)

ubuntu: `sudo docker-compose -f /home/ubuntu/docker/unifi-controller.yml up`
macOS: `docker-compose up`

## Docker logs
from the ubuntu system (which is where I want it to work):

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
WARN Unable to load properties from '/usr/lib/unifi/data/system.properties' - /usr/lib/unifi/data/system.properties (No such file or directory)
org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: destroy called
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by TheSpad** [comment]
The first warning is expected as the file doesn't exist on first boot.

The subsequent errors are *because* you're mounting an empty host volume to /var/lib/unifi

I suspect you're just being impatient, the container can take a long time to start on first boot, especially on slower devices. On average you'd expect the webui to be available within a couple of minutes.

**Comment by marksherman** [comment]
> ... the container can take a long time to start on first boot, especially on slower devices. 

Please accept my humblest apologies. You're right. It takes some amount of time after the log settles before it's fully done baking. 

This is resolved.
