### ISSUE TITLE
MongoDB is accessible to all local users (exposing sensitive information) when container is using host networking

### ISSUE THREAD

**Issue by ghost** [linuxserver/docker-unifi-controller#89]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior
When using host networking, the MongoDB database configured for the Unifi Controller should not be accessible to all local users. All users should need to provide proper credentials to access the MongoDB instance. Without enabling authentication, any user is able to view (and possibly edit) the ace databases for the UniFi Controller.

## Current Behavior
Executing `mongo --port 27117` allows a user to connect to the MongoDB instance without authenticating. Executing `use ace` followed by `db.wlanconf.find()` or `db.admin.find()` allows a user to identify sensitive information like WiFi passwords, admin password hashes, etc.

## Steps to Reproduce
1. Create a docker compose file or ansible playbook to create the container using `network_mode: host`
2. Execute `docker exec -it <container_name> bash` to gain shell access to the container. (NOTE: This can be performed on the host if mongo client is installed; this demonstration uses the mongo application in the container instead.)
3. Execute `mongo --port 27117` to access the database.
4. Execute `use ace` to access the database for the UniFi Controller. Run any of the commands listed in the previous section to view sensitive information.

## Environment
**OS:** Ubuntu 20.04
**CPU architecture:** x86_64
**How docker service was installed:** Installed from ghcr.io image using Ansible playbook.

## Command used to create docker container (run/create/compose/screenshot)
Ansible playbook utilized. I don't think it's necessary to include it here.

## Docker logs
No logs required.

**Comment by j0nnymoe** [comment]
To my knowledge, we're setting up mongodb as unifi instructing: https://help.ui.com/hc/en-us/articles/220066768-UniFi-Network-How-to-Install-and-Update-via-APT-on-Debian-or-Ubuntu for example.
I suspect if you enabled any sort of authentication on mongodb, unifi will break.

It's an interesting issue though, thanks for raising.

**Comment by hoffmanpm2** [comment]
Interesting article. I did some digging and I'd expect there would need to be parameters added to data/system.properties. I don't currently see any documentation for specifying authentication credentials for the mongodb though.

**Comment by djmattyg007** [comment]
This doesn't look stale to me.
