### ISSUE TITLE
Rename to Unifi Network Application

### ISSUE THREAD

**Issue by ferferga** [linuxserver/docker-unifi-controller#91]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Ubiquiti has renamed *Unifi Controller* to *Unifi Network Application*. In order to not confuse users, this image should be renamed as well I guess.

Also, old packages stored under the older GitHub Docker registry should be removed, in order to not confuse users.

### Source

* [Official docs](https://help.ui.com/hc/en-us/articles/1500012237441-UniFi-Network-Use-the-UniFi-Network-Application)
* [Release Notes comments](https://community.ui.com/releases/UniFi-Network-Application-6-2-23/55d0375e-86cd-4922-ad91-786a2e4b0bb5#comment/020efaf3-0d47-4248-8054-275d546e816a)
* [Reddit's unofficial community](https://www.reddit.com/r/Ubiquiti/comments/ngjjf1/controller_vs_network_application/gyrfqux?utm_source=share&utm_medium=web2x&context=3)

**Comment by ferferga** [comment]
Bump

**Comment by ferferga** [comment]
Bump

**Comment by ferferga** [comment]
Bump

**Comment by Jc2k** [comment]
Bump

**Comment by j0nnymoe** [comment]
We're aware of the name change but currently no plans to do this as it wouldn't just be a case of renaming the repo and being done.

**Comment by ferferga** [comment]
@j0nnymoe No rush to do this ofc but, at least, can this be labeled as confirmed so stale action leaves it alone?

**Comment by drizuid** [comment]
the issue IS stale because we have no plans to do this..
