### ISSUE TITLE
latest Unifi-Controller not working on odroidxu4

### ISSUE THREAD

**Issue by redespace** [linuxserver/docker-unifi-controller#96]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Able to open GUI at 8443

## Current Behavior

When starting the container, it seems Unifi crashes

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:** OMV 4
**CPU architecture:** arm64
**How docker service was installed:**

OS Provided

## Command used to create docker container (run/create/compose/screenshot)

---
version: "2.1"
networks:
  Home:
    external:
      name: Home
services:
  unifi-controller:
    image: ghcr.io/linuxserver/unifi-controller
    container_name: unifi-controller

    environment:
      - PUID=1000
      - PGID=100
    volumes:
      - /sharedfolders/Sys_Backup/OMV/appdata/Unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    networks:
      Home:
        ipv4_address: 192.168.1.250
    restart: unless-stopped

## Docker logs

[Container Logs](https://pastebin.com/94f5DFr1)

**Comment by drizuid** [comment]
can you provide the output of `uname -m`

**Comment by redespace** [comment]
> can you provide the output of `uname -m`

aarch64

**Comment by j0nnymoe** [comment]
Old Issue, will close as assuming (rightly or wrongly) it's not longer an issue. 

If this is still indeed an issue, please re-open a new issue and provide logs for the container and unifi itself.
