### ISSUE TITLE
Option to run without MongoDB

### ISSUE THREAD

**Issue by lepatrick** [linuxserver/docker-unifi-controller#97]
Hey Guys,

for a long time I run the UniFi Controller directly in my Pi 3B+. Now I switched to Pi4 and migrated to Docker.

On the old Pi 3 I disabled mongoDB after installation of UniFi with:
`sudo systemctl disable mongodb && sudo systemctl stop mongodb`

UniFi Controller worked without any problems. It would be great to give the container the an option without mongoDB. I think it's fine for smaller networks and SD-Card will live longer time.

**Comment by drizuid** [comment]
closing as running unifi-controller without mongodb is not officially supported by upstream.
