### ISSUE TITLE
MongoDB not working with data volume on NFS mount

### ISSUE THREAD

**Issue by sotiris-bos** [linuxserver/docker-unifi-controller#98]
Hello, I am just parking this here in case anyone else has this issue.

I don't know if this was always the problem or if it came up in a recent update.

I have been fighting a Unifi controller container all day. It used to be v5.13.32 and it stopped working. I tried to update to any of the more recent versions to no avail.

It seems as MongoDB does not work when the data volume is on an NFS share. This is not a permissions issue.

When the data volume is on the NFS share, MongoDB keeps restarting with: `shutting down with code:100` in the mongodb log file.

When I move the data volume to local storage, the controller works fine.

**Comment by lawliet89** [comment]
Not stale. Experiencing this.

**Comment by aptalca** [comment]
We don't support or recommend putting the config folder on a remote share due to issues like the one you're experiencing. Databases don't like to on the mounts so there is nothing for us to change/fix here.
